export_languages:
  - english
files:
  - source: /admin/includes/languages/lang.english.php
    translation: /admin/includes/languages/lang.%language%.php
    update_option: update_as_unapproved
  - source: /admin/includes/languages/english/*.php
    translation: /admin/includes/languages/%language%/%original_file_name%
    update_option: update_as_unapproved
  - source: /admin/includes/languages/english/extra_definitions/*.php
    translation: /admin/includes/languages/%language%/extra_definitions/%original_file_name%
    update_option: update_as_unapproved
  - source: /admin/includes/languages/english/modules/newsletters/*.php
    translation: /admin/includes/languages/%language%/modules/newsletters/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/lang.english.php
    translation: /includes/languages/lang.%language%.php
    update_option: update_as_unapproved
  - source: /includes/languages/english/*.php
    translation: /includes/languages/%language%/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/classic/*.php
    translation: /includes/languages/%language%/classic/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/extra_definitions/*.php
    translation: /includes/languages/%language%/extra_definitions/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/extra_definitions/classic/*.php
    translation: /includes/languages/%language%/extra_definitions/classic/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/extra_definitions/responsive_classic/*.php
    translation: /includes/languages/%language%/extra_definitions/responsive_classic/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/html_includes/*.php
    dest: /includes/languages/english/html_includes/%file_name%.txt
    translation: /includes/languages/%language%/html_includes/%file_name%.php
    update_option: update_as_unapproved
  - source: /includes/languages/english/html_includes/classic/*.php
    dest: /includes/languages/english/html_includes/classic/%file_name%.txt
    translation: /includes/languages/%language%/html_includes/classic/%file_name%.php
    update_option: update_as_unapproved
  - source: /includes/languages/english/html_includes/responsive_classic/*.php
    dest: /includes/languages/english/html_includes/responsive_classic/%file_name%.txt
    translation: /includes/languages/%language%/html_includes/responsive_classic/%file_name%.php
    update_option: update_as_unapproved
  - source: /includes/languages/english/modules/order_total/*.php
    translation: /includes/languages/%language%/modules/order_total/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/modules/payment/*.php
    translation: /includes/languages/%language%/modules/payment/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/modules/shipping/*.php
    translation: /includes/languages/%language%/modules/shipping/%original_file_name%
    update_option: update_as_unapproved
  - source: /includes/languages/english/responsive_classic/*.php
    translation: /includes/languages/%language%/responsive_classic/%original_file_name%
    update_option: update_as_unapproved
