<?php

namespace Database\Seeders\zencart;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LayoutBoxesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('layout_boxes')->truncate();

        DB::table('layout_boxes')->insert(array(
            0 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box_all.php',
                    'layout_box_sort_order' => 5,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 1,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            1 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'banner_box.php',
                    'layout_box_sort_order' => 300,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 127,
                    'layout_id' => 2,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            2 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box2.php',
                    'layout_box_sort_order' => 15,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 15,
                    'layout_id' => 3,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            3 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'best_sellers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 70,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 4,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            4 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'categories.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 10,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 5,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            5 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'currencies.php',
                    'layout_box_sort_order' => 80,
                    'layout_box_sort_order_single' => 60,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 6,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            6 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'document_categories.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 7,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            7 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'ezpages.php',
                    'layout_box_sort_order' => -1,
                    'layout_box_sort_order_single' => 2,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 8,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            8 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'featured.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 9,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            9 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'information.php',
                    'layout_box_sort_order' => 50,
                    'layout_box_sort_order_single' => 40,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 10,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            10 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'languages.php',
                    'layout_box_sort_order' => 70,
                    'layout_box_sort_order_single' => 50,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 11,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            11 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'manufacturers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 20,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 12,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            12 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'manufacturer_info.php',
                    'layout_box_sort_order' => 35,
                    'layout_box_sort_order_single' => 95,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 13,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            13 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'more_information.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 14,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            14 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'music_genres.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 15,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            15 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'order_history.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 16,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            16 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'product_notifications.php',
                    'layout_box_sort_order' => 55,
                    'layout_box_sort_order_single' => 85,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 17,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            17 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'record_companies.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 18,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            18 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'reviews.php',
                    'layout_box_sort_order' => 40,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 19,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            19 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'search.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 20,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            20 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'search_header.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 1,
                    'layout_id' => 21,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            21 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'shopping_cart.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 30,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 22,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            22 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'specials.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 23,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            23 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'whats_new.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 24,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            24 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'whos_online.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 25,
                    'layout_template' => 'default_template_settings',
                    'plugin_details' => '',
                ),
            25 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box_all.php',
                    'layout_box_sort_order' => 5,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 26,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            26 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'banner_box.php',
                    'layout_box_sort_order' => 300,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 127,
                    'layout_id' => 27,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            27 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box2.php',
                    'layout_box_sort_order' => 15,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 15,
                    'layout_id' => 28,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            28 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'best_sellers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 70,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 29,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            29 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'categories.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 10,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 30,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            30 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'currencies.php',
                    'layout_box_sort_order' => 80,
                    'layout_box_sort_order_single' => 60,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 31,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            31 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'ezpages.php',
                    'layout_box_sort_order' => -1,
                    'layout_box_sort_order_single' => 2,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 32,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            32 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'featured.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 33,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            33 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'information.php',
                    'layout_box_sort_order' => 50,
                    'layout_box_sort_order_single' => 40,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 34,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            34 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'languages.php',
                    'layout_box_sort_order' => 70,
                    'layout_box_sort_order_single' => 50,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 35,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            35 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'manufacturers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 20,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 36,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            36 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'manufacturer_info.php',
                    'layout_box_sort_order' => 35,
                    'layout_box_sort_order_single' => 95,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 37,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            37 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'more_information.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 38,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            38 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'my_broken_box.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 39,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            39 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'order_history.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 40,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            40 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'product_notifications.php',
                    'layout_box_sort_order' => 55,
                    'layout_box_sort_order_single' => 85,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 41,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            41 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'reviews.php',
                    'layout_box_sort_order' => 40,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 42,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            42 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'search.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 43,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            43 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'search_header.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 1,
                    'layout_id' => 44,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            44 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'shopping_cart.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 30,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 45,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            45 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'specials.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 46,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            46 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'whats_new.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 47,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            47 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'whos_online.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 48,
                    'layout_template' => 'template_default',
                    'plugin_details' => '',
                ),
            48 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'banner_box.php',
                    'layout_box_sort_order' => 300,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 127,
                    'layout_id' => 49,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            49 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box2.php',
                    'layout_box_sort_order' => 15,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 15,
                    'layout_id' => 50,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            50 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box_all.php',
                    'layout_box_sort_order' => 5,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 51,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            51 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'best_sellers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 70,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 52,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            52 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'categories.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 10,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 53,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            53 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'currencies.php',
                    'layout_box_sort_order' => 80,
                    'layout_box_sort_order_single' => 60,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 54,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            54 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'document_categories.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 55,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            55 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'ezpages.php',
                    'layout_box_sort_order' => -1,
                    'layout_box_sort_order_single' => 2,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 56,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            56 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'featured.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 57,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            57 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'information.php',
                    'layout_box_sort_order' => 50,
                    'layout_box_sort_order_single' => 40,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 58,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            58 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'languages.php',
                    'layout_box_sort_order' => 70,
                    'layout_box_sort_order_single' => 50,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 59,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            59 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'manufacturers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 20,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 60,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            60 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'manufacturer_info.php',
                    'layout_box_sort_order' => 35,
                    'layout_box_sort_order_single' => 95,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 61,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            61 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'more_information.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 62,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            62 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'music_genres.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 63,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            63 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'order_history.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 64,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            64 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'product_notifications.php',
                    'layout_box_sort_order' => 55,
                    'layout_box_sort_order_single' => 85,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 65,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            65 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'record_companies.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 66,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            66 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'reviews.php',
                    'layout_box_sort_order' => 40,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 67,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            67 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'search.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 68,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            68 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'search_header.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 1,
                    'layout_id' => 69,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            69 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'shopping_cart.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 30,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 70,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            70 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'specials.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 71,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            71 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'whats_new.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 72,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            72 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'whos_online.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 73,
                    'layout_template' => 'classic',
                    'plugin_details' => '',
                ),
            73 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'banner_box.php',
                    'layout_box_sort_order' => 300,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 127,
                    'layout_id' => 74,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            74 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box2.php',
                    'layout_box_sort_order' => 15,
                    'layout_box_sort_order_single' => 1,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 15,
                    'layout_id' => 75,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            75 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'banner_box_all.php',
                    'layout_box_sort_order' => 5,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 76,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            76 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'best_sellers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 70,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 77,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            77 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'categories.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 10,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 78,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            78 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'currencies.php',
                    'layout_box_sort_order' => 80,
                    'layout_box_sort_order_single' => 60,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 79,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            79 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'document_categories.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 80,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            80 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'ezpages.php',
                    'layout_box_sort_order' => -1,
                    'layout_box_sort_order_single' => 2,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 81,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            81 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'featured.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 82,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            82 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'information.php',
                    'layout_box_sort_order' => 50,
                    'layout_box_sort_order_single' => 40,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 83,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            83 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'languages.php',
                    'layout_box_sort_order' => 70,
                    'layout_box_sort_order_single' => 50,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 0,
                    'layout_id' => 84,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            84 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'manufacturers.php',
                    'layout_box_sort_order' => 30,
                    'layout_box_sort_order_single' => 20,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 85,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            85 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'manufacturer_info.php',
                    'layout_box_sort_order' => 35,
                    'layout_box_sort_order_single' => 95,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 86,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            86 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'more_information.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 87,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            87 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'music_genres.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 88,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            88 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'order_history.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 89,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            89 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'product_notifications.php',
                    'layout_box_sort_order' => 55,
                    'layout_box_sort_order_single' => 85,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 90,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            90 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'record_companies.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 91,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            91 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'reviews.php',
                    'layout_box_sort_order' => 40,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 92,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            92 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'search.php',
                    'layout_box_sort_order' => 10,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 93,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            93 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'search_header.php',
                    'layout_box_sort_order' => 0,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 0,
                    'layout_box_status_single' => 1,
                    'layout_id' => 94,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            94 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'shopping_cart.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 30,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 95,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            95 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'specials.php',
                    'layout_box_sort_order' => 45,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 96,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            96 =>
                array(
                    'layout_box_location' => 0,
                    'layout_box_name' => 'whats_new.php',
                    'layout_box_sort_order' => 20,
                    'layout_box_sort_order_single' => 0,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 0,
                    'layout_id' => 97,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
            97 =>
                array(
                    'layout_box_location' => 1,
                    'layout_box_name' => 'whos_online.php',
                    'layout_box_sort_order' => 200,
                    'layout_box_sort_order_single' => 200,
                    'layout_box_status' => 1,
                    'layout_box_status_single' => 1,
                    'layout_id' => 98,
                    'layout_template' => 'responsive_classic',
                    'plugin_details' => '',
                ),
        ));


    }
}
