Feature: Customer Group Discounts
  Test the use of Group Discounts in catalog


  Scenario: I Test group discounts
    Given I set customer "default_customer_email" to group discount id "1"
    Then I create a discount coupon "test10percent"
    Then I do a standard customer login with <param>"default_customer_email", <param>"default_customer_password"
    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "storepickup_storepickup0" from "shipping"
    And I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I select "cod" from "payment"
    And I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "39.99"
    And I should see "-$4.00"
    And I should see "2.52"
    Then I should see "38.51"
    Then I press button "btn_submit"

    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "storepickup_storepickup0" from "shipping"
    And I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    Then I fill in "dc_redeem_code" with "test10percent"
    And I select "cod" from "payment"
    And I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "39.99"
    And I should see "-$4.00"
    And I should see "-$3.60"
    And I should see "2.27"
    Then I should see "34.66"
    Then I press button "btn_submit"

    Given I switch to tax "inclusive"

    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "storepickup_storepickup0" from "shipping"
    And I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I select "cod" from "payment"
    And I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "42.79"
    And I should see "-$4.28"
    And I should see "2.52"
    Then I should see "38.51"
    Then I press button "btn_submit"

    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "storepickup_storepickup0" from "shipping"
    And I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    Then I fill in "dc_redeem_code" with "test10percent"
    And I select "cod" from "payment"
    And I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "42.79"
    And I should see "-$4.28"
    And I should see "-$3.85"
    And I should see "2.27"
    Then I should see "34.66"
    Then I press button "btn_submit"

    Given I switch flat shipping tax "on"

    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "flat_flat" from "shipping"
    And I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I select "cod" from "payment"
    And I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "42.79"
    And I should see "-$4.28"
    And I should see "3.47"
    Then I should see "44.46"
    Then I press button "btn_submit"

    Given I switch split tax mode "on"
    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "flat_flat" from "shipping"
    And I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I select "cod" from "payment"
    And I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "42.79"
    Then I should see "5.95"
    And I should see "-$4.28"
    And I should see "2.52"
    And I should see "0.95"
    Then I should see "44.46"
    Then I press button "btn_submit"

    Given I switch split tax mode "off"
    Then I switch flat shipping tax "off"
    Then I switch to tax "non-inclusive"
    Then I set customer "default_customer_email" to group discount id "0"
