Feature: Low Order Fee
  Test the use of low order fees in catalog

  Scenario: I Test low order fees

    Given I ensure gift voucher balance is "300" for customer "default_customer_email", "default_customer_password"
    Then I set customer "default_customer_email" to group discount id "1"
    Then I switch item shipping tax "off"
    And I switch low order fee "on"
    And I do a standard customer login with <param>"default_customer_email", <param>"default_customer_password"

    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    Then I select "cod" from "payment"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "39.99"
    Then I should see "$2.50"
    Then I should see "$2.52"
    Then I should see "$5.00"
    Then I should see "46.01"
    Then I press button "btn_submit"

    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I fill in "cot_gv" with "45.28"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "Please select a payment method for your order"


    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I fill in "cot_gv" with "45.29"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "Please select a payment method for your order"


    Then I switch item shipping tax "on"
    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I fill in "cot_gv" with "45.76"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "Please select a payment method for your order"
    Then I switch item shipping tax "off"


    Then I switch item shipping tax "on"
    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I fill in "cot_gv" with "46.48"
    Then I select "cod" from "payment"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "39.99"
    Then I should see "2.50"
    Then I should see "2.99"
    Then I should see "5.00"
    Then I should see "-$46.48"
    Then I should see "$0.00"
    Then I switch item shipping tax "off"


    Given I switch item shipping tax "on"
    Then I switch to tax "inclusive"

    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I fill in "cot_gv" with "46.48"
    Then I select "cod" from "payment"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"

    Then I should see "42.79"
    Then I should see "2.98"
    Then I should see "-$4.28"
    Then I should see "2.99"
    Then I should see "5.00"
    Then I should see "-$46.48"
    Then I should see "$0.00"

    Then I switch to tax "non-inclusive"
    Then I switch item shipping tax "off"


    Given I set customer "default_customer_email" to group discount id "1"
    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    Then I select "cod" from "payment"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "39.99"
    Then I should see "2.50"
    Then I should see "-$4.00"
    Then I should see "2.52"
    Then I should see "5.00"
    Then I should see "46.01"
    Then I set customer "default_customer_email" to group discount id "0"


    Given I set customer "default_customer_email" to group discount id "1"
    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I fill in "cot_gv" with "45.29"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "Please select a payment method for your order"
    Given I set customer "default_customer_email" to group discount id "0"

    Given I create a discount coupon "test10percent"
    Then I visit "index.php?main_page=shopping_cart&action=empty_cart"
    And I visit "index.php?main_page=product_info&cPath=1_9&products_id=3&action=buy_now"
    And I visit "index.php?main_page=checkout_shipping"
    Then I select "item_item" from "shipping"
    Then I click on the element with xpath "//*[@id='checkoutShipping']/form/div[5]/input"
    And I fill in "cot_gv" with "46.01"
    And I fill in "dc_redeem_code" with "test10percent"
    Then I select "cod" from "payment"
    Then I click on the element with css "#paymentSubmit > input[type='submit']"
    Then I should see "39.99"
    Then I should see "2.50"
    Then I should see "-$4.00"
    Then I should see "2.52"
    Then I should see "5.00"
    Then I should see "$46.01"

    Then I switch low order fee "off"
    Then I set customer "default_customer_email" to group discount id "0"
