<?php
/**
 * Package Tracking Shipper List for the PayPalRestful (paypalr) Payment Module
 *
 * @copyright Copyright 2023-2025 Zen Cart Development Team
 * @license https://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 *
 * Last updated: v1.2.0
 */

namespace PayPalRestful\Common;

class PayPalShippingCarriers
{
    /**
     * Determine whether the given carrier code is valid with PayPal
     *
     * @param string $carrier_code
     * @return bool
     */
    public static function isValid(string $carrier_code): bool
    {
        foreach (explode(';', self::carriersCsv) as $line) {
            if (empty($line)) {
                continue;
            }
            [$name, $code, $country] = explode(',', trim($line));
            if ($code === 'OTHER') {
                continue;
            }
            if ($code === $carrier_code) {
                return true;
            }
        }
        return false;
    }

    public static function findBestMatch(string $carrier_name, string $country_iso_3 = ''): ?string
    {
        $carrier_name = \strtoupper($carrier_name);
        if ($carrier_name === 'OTHER') {
            return 'OTHER';
        }

        $bestMatch = '';
        $carriersForCountry = self::getCarriersForCountry($country_iso_3, true);
        $carriersForCountry = \array_change_key_case($carriersForCountry, \CASE_UPPER);

        // if we have an exact match on code, just return it
        if (\array_key_exists($carrier_name, $carriersForCountry)) {
            return $carrier_name;
        }

        // find longest-matching name
        foreach ($carriersForCountry as $code => $name) {
            $name = \strtoupper($name);
            if (str_contains($carrier_name, $name)) {
                if (strlen($name) > strlen($bestMatch)) {
                    $bestMatch = $name;
                }
            }
        }

        // return the code for the best-matching name
        if (!empty($bestMatch)) {
            foreach ($carriersForCountry as $code => $name) {
                if ($bestMatch === \strtoupper($name)) {
                    return $code;
                }
            }
        }

        return null;
    }

    /**
     * Lookup available carriers by country code.
     *
     * @param string $country_iso_3 Filter by country's 3-char ISO code, or 'GLOBAL'
     * @param bool $withGlobal Include global carriers as well? Globals appear after country-specific
     * @return array
     */
    public static function getCarriersForCountry(string $country_iso_3, bool $withGlobal = false): array
    {
        $found = [];
        $globals = [];
        foreach (explode(';', self::carriersCsv) as $line) {
            if (empty($line)) {
                continue;
            }
            [$name, $code, $country] = explode(',', trim($line));
            if ($code === 'OTHER') {
                continue;
            }
            if ($country === $country_iso_3) {
                $found[$code] = $name;
            }
            $globals[$code] = $name;
        }
        if (empty($found)) {
            return $globals;
        }
        if ($withGlobal === false) {
            return $found;
        }
        // put globals after local carriers
        return array_merge($found, $globals);
    }

    /**
     * Valid carrier codes per https://developer.paypal.com/docs/tracking/reference/carriers/
     * Scraped and parsed July 2025
     */
    public const carriersCsv = <<<'CSV'
A2B Express Logistics,A2B_BA,GLOBAL;
ACI Logistix,ACILOGISTIX,GLOBAL;
ACOMMERCE,ACOMMERCE,GLOBAL;
ADS Express,ADS,GLOBAL;
AEROFLASH,AEROFLASH,GLOBAL;
AIR 21,AIR_21,GLOBAL;
AIRSPEED,AIRSPEED,GLOBAL;
Airterra,AIRTERRA,GLOBAL;
Allegro,ALLEGRO,GLOBAL;
ALLJOY SUPPLY CHAIN,ALLJOY,GLOBAL;
Amazon,AMAZON_EMAIL_PUSH,GLOBAL;
Amazon UK API,AMAZON_UK_API,GLOBAL;
AMS Group,AMS_GRP,GLOBAL;
Anteraja,ANTERAJA,GLOBAL;
Aramex,ARAMEX,GLOBAL;
Asendia DE,ASENDIA_DE,GLOBAL;
Asendia Global,ASENDIA,GLOBAL;
Associated Couriers,ASSOCIATED_COURIERS,GLOBAL;
ATA,ATA,GLOBAL;
ATS Healthcare,ATSHEALTHCARE,GLOBAL;
Au Express,AUEXPRESS,GLOBAL;
Averitt Express,AVERITT,GLOBAL;
AxleHire,AXLEHIRE,GLOBAL;
BDMnet,BDMNET,GLOBAL;
Bel Belgium Post,BEL_BELGIUM_POST,GLOBAL;
Belpost,BLR_BELPOST,GLOBAL;
BERT,BERT,GLOBAL;
Better Trucks,BETTERTRUCKS,GLOBAL;
Big Smart,BIGSMART,GLOBAL;
BJS Distribution courier,BJSHOMEDELIVERY,GLOBAL;
BLUEDART,BLUEDART,GLOBAL;
Bollore Logistics,BOLLORE_LOGISTICS,GLOBAL;
Bpost international,BPOST_INT,GLOBAL;
BUFFALO,BUFFALO,GLOBAL;
Burd Delivery,BURD,GLOBAL;
Cago,CAGO,GLOBAL;
CANPAR,CANPAR,GLOBAL;
Capital Transport,CAPITAL,GLOBAL;
Carry-Flap Co.,CARRY_FLAP,GLOBAL;
CDL Last Mile,CDLDELIVERS,GLOBAL;
CEVA LOGISTICS,CEVA,GLOBAL;
CJ GLS,CJ_GLS,GLOBAL;
CJ Logistics International,CJ_LOGISTICS,GLOBAL;
CJ Philippines,CJ_PHILIPPINES,GLOBAL;
CN Logistics,CN_LOGISTICS,GLOBAL;
COLLECTPLUS,COLLECTPLUS,GLOBAL;
ComOne Express,COM1EXPRESS,GLOBAL;
Copa Airlines Courier,COPA_COURIER,GLOBAL;
Coretrails,CORETRAILS,GLOBAL;
Correos Express (www.correos.es),CORREOS_ES,GLOBAL;
Corriere Franco,FRANCO,GLOBAL;
COURIER POST,COURIER_POST,GLOBAL;
COURIERPLUS,COURIERPLUS,GLOBAL;
CRL Express,CRLEXPRESS,GLOBAL;
Crossflight Limited,CROSSFLIGHT,GLOBAL;
DACHSER,DACHSER,GLOBAL;
Daeshin,DAESHIN,GLOBAL;
Daiichi Freight System Inc,DAIICHI,GLOBAL;
Danniao,DANNIAO,GLOBAL;
Day & Ross,DAYROSS,GLOBAL;
Daylight Transport,DYLT,GLOBAL;
DD Express Courier,DDEXPRESS,GLOBAL;
DE DHL,DE_DHL,GLOBAL;
Deliver Your Parcel,DELIVERYOURPARCEL_ZA,GLOBAL;
Deliver-iT,DELIVER_IT,GLOBAL;
Delivere,DELIVERE,GLOBAL;
DELTEC DE,DELTEC_DE,GLOBAL;
Dependable Supply Chain Services,GODEPENDABLE,GLOBAL;
Deutsche DE,DEUTSCHE_DE,GLOBAL;
DHL Active Tracing,DHL_ACTIVE_TRACING,GLOBAL;
DHL eCommerce Greater China,DHL_ECOMMERCE_GC,GLOBAL;
DHL Freight,DHL_FREIGHT,GLOBAL;
Dhl Global,DHL,GLOBAL;
Dhl Global Mail,DHL_GLOBAL_MAIL,GLOBAL;
DHL International,IT_DHL_ECOMMERCE,GLOBAL;
DHL Parcel NL,DHL_PARCEL_NL,GLOBAL;
Dhl Pieceid,DHL_PIECEID,GLOBAL;
Dhl Supply Chain AU,DHL_SUPPLY_CHAIN_AU,GLOBAL;
DHL Supply Chain Indonesia,DHL_SUPPLYCHAIN_ID,GLOBAL;
Dhlparcel UK,DHLPARCEL_UK,GLOBAL;
Dialogo Logistica,DIALOGO_LOGISTICA,GLOBAL;
Direx,DIREX,GLOBAL;
Discount Post,DISCOUNTPOST,GLOBAL;
DMF,DMFGROUP,GLOBAL;
DPD,DPD,GLOBAL;
Dpd DE,DPD_DE,GLOBAL;
DPD delistrack,DPD_DELISTRACK,GLOBAL;
DPD Netherlands,DPD_NL,GLOBAL;
Dpd UK,DPD_UK,GLOBAL;
DPEX,CN_DPEX,GLOBAL;
DPEX (www.dpex.com),DPEX,GLOBAL;
DSV courier,DSV,GLOBAL;
DX,DX,GLOBAL;
DX Freight,DX_FREIGHT,GLOBAL;
EasyRoutes,EASYROUTES,GLOBAL;
ECARGO,ECARGO,GLOBAL;
ECexpress,ECEXPRESS,GLOBAL;
ECMS International Logistics Co.,ECMS,GLOBAL;
Eco Freight,ECOFREIGHT,GLOBAL;
Ecoutier,ECOUTIER,GLOBAL;
Ecparcel,ECPARCEL,GLOBAL;
EFS (E-commerce Fulfillment Service),EFS,GLOBAL;
Elta GR,ELTA_GR,GLOBAL;
Emirates Post,ARE_EMIRATES_POST,GLOBAL;
EMS,EMS,GLOBAL;
Ems CN,EMS_CN,GLOBAL;
Energo Logistic,ENERGOLOGISTIC,GLOBAL;
Etomars,ETOMARS,GLOBAL;
Etonas,ETONAS,GLOBAL;
Etotal Solution Limited,ETOTAL,GLOBAL;
Etower,ETOWER,GLOBAL;
Eurodis,EURODIS,GLOBAL;
EWE Global Express,EWE,GLOBAL;
Expeditors,EXPEDITORS,GLOBAL;
Fast & Furious,FNF_ZA,GLOBAL;
Fast Despatch Logistics Limited,FASTDESPATCH,GLOBAL;
Fastbox,FASTBOX,GLOBAL;
Fastship Express,FASTSHIP,GLOBAL;
Fasttrack,FASTTRACK,GLOBAL;
Fastway AU,FASTWAY_AU,GLOBAL;
Fastway ZA,FASTWAY_ZA,GLOBAL;
FedExÆ Freight,FEDEX_FR,GLOBAL;
Fercam IT,FERCAM_IT,GLOBAL;
Fin Mile,FINMILE,GLOBAL;
Flight Logistics Group,FLIGHTLG,GLOBAL;
FlipXpress,FLIPXP,GLOBAL;
FLYTEXPRESS,FLYTEXPRESS,GLOBAL;
Forward Air,FORWARDAIR,GLOBAL;
FOUR PX EXPRESS,FOUR_PX_EXPRESS,GLOBAL;
Fourkites,FOURKITES,GLOBAL;
FR Colissimo,FR_COLISSIMO,GLOBAL;
FR Mondial,FR_MONDIAL,GLOBAL;
FRONTdoor Collective,FRONTDOORCORP,GLOBAL;
FUJIE EXPRESS,FUJEXP,GLOBAL;
GDPharm Logistics,GDPHARM,GLOBAL;
GEODIS,GEODIS,GLOBAL;
Georgian Post,GPOST,GLOBAL;
Giao h‡ng nhanh,GIAO_HANG,GLOBAL;
GIO Express Inc,GIO_ECOURIER,GLOBAL;
Global Post,GOGLOBALPOST,GLOBAL;
GLOBEGISTICS,GLOBEGISTICS,GLOBAL;
GLS,GLS,GLOBAL;
Gls Spain,GLS_SPAIN,GLOBAL;
GO Logistics & Storage,GOLS,GLOBAL;
Go People,GOPEOPLE,GLOBAL;
Go Rush,GORUSH,GLOBAL;
GoBolt,GOBOLT,GLOBAL;
Gofo Express,GOFO_EXPRESS,GLOBAL;
GPS,GPS,GLOBAL;
GREYHOUND,GREYHOUND,GLOBAL;
HanJin,HANJIN,GLOBAL;
Hellenic (Greece) Post,HELLENIC_POST,GLOBAL;
Hellmann Worldwide Logistics,HELLMANN,GLOBAL;
Hepsijet,HEPSIJET,GLOBAL;
Hermesworld UK,HERMESWORLD_UK,GLOBAL;
Hero Express,HEROEXPRESS,GLOBAL;
HFD,HFD,GLOBAL;
HK Rpx,HK_RPX,GLOBAL;
HSDEXPRESS,HSDEXPRESS,GLOBAL;
HuanTong,HUANTONG,GLOBAL;
HUBBED,HUBBED,GLOBAL;
Iceland Post,POSTUR_IS,GLOBAL;
ICS COURIER,ICSCOURIER,GLOBAL;
Idexpress Indonesia,IDEXPRESS_ID,GLOBAL;
Idn Pos,IDN_POS,GLOBAL;
IML courier,IML,GLOBAL;
IMX,IMX,GLOBAL;
India Post Domestic,INDIA_POST,GLOBAL;
India Post International,INDIA_POST_INT,GLOBAL;
InPost,INPOST_UK,GLOBAL;
INTERSMARTTRANS & SOLUTIONS SL,INTERSMARTTRANS,GLOBAL;
INTEX Paketdienst GmbH,INTEX_DE,GLOBAL;
Ithink Logistics,ITHINKLOGISTICS,GLOBAL;
J&T CARGO,JTCARGO,GLOBAL;
J&T Express Philippines,JTEXPRESS_PH,GLOBAL;
Jadlog,JADLOG,GLOBAL;
JCEX courier,CN_JCEX,GLOBAL;
JD Worldwide,JD_WORLDWIDE,GLOBAL;
Jersey Post Group,JERSEYPOST_ATLAS,GLOBAL;
Jetship My,JETSHIP_MY,GLOBAL;
JNE Express (Jalur Nugraha Ekakurir),IDN_JNE,GLOBAL;
Joyingbox,JOYINGBOX,GLOBAL;
JUSDASR,JUSDASR,GLOBAL;
KargomKolay (CargoMini),KARGOMKOLAY,GLOBAL;
KedaEX,KEDAEX,GLOBAL;
Kerry Express Hong Kong,HK_TGX,GLOBAL;
Kerry Express Thailand,THA_KERRY,GLOBAL;
Keuhne + Nagel Global,KNG,GLOBAL;
Kolay Gelsin,KOLAY_GELSIN,GLOBAL;
Komon Express,KOMON_EXPRESS,GLOBAL;
Kronos Express,KRONOS,GLOBAL;
Kuehne + Nagel,KUEHNE,GLOBAL;
LIEFERGRUN,LIEFERGRUN,GLOBAL;
Lietuvos pastas,LTU_LIETUVOS,GLOBAL;
Link Bridge(BeiJing)international logistics co.,LINKBRIDGE,GLOBAL;
LION PARCEL,LION_PARCEL,GLOBAL;
LOGISTICSWORLDWIDE KR,LOGISTICSWORLDWIDE_KR,GLOBAL;
LOGISTICSWORLDWIDE MY,LOGISTICSWORLDWIDE_MY,GLOBAL;
LogoiX,LOGOIX,GLOBAL;
Logwin Logistics,LOGWIN_LOGISTICS,GLOBAL;
Luwjistik,LUWJISTIK,GLOBAL;
M&X cargo,MX_CARGO,GLOBAL;
M3 Logistics,M3LOGISTICS,GLOBAL;
Madrooex,MADROOEX,GLOBAL;
Malaysia Post EMS / Pos Laju,MYS_EMS,GLOBAL;
Malca-Amit,MALCA_AMIT,GLOBAL;
Med Africa Logistics,MEDAFRICA,GLOBAL;
Meest,MEEST,GLOBAL;
Mhi,MHI,GLOBAL;
Mikropakket,MIKROPAKKET,GLOBAL;
MISUMI Group Inc.,MISUMI_CN,GLOBAL;
MNG Kargo,MNG_KARGO,GLOBAL;
Mobi Logistica,MOBI_BR,GLOBAL;
Moovin,MOOVIN,GLOBAL;
Morning Global,MORNINGLOBAL,GLOBAL;
Movianto,MOVIANTO,GLOBAL;
MUDITA,MUDITA,GLOBAL;
My DynaLogic,MYDYNALOGIC,GLOBAL;
N&M Transfer Co. Inc.,NMTRANSFER,GLOBAL;
Netlogix,NETLOGIXGROUP,GLOBAL;
NEW ZEALAND COURIERS,NEWZEALAND_COURIERS,GLOBAL;
Newgistics,NEWGISTICS,GLOBAL;
Newgistics API,NEWGISTICSAPI,GLOBAL;
Nightline UK,NIGHTLINE_UK,GLOBAL;
NimbusPost,NIMBUSPOST,GLOBAL;
Nippon Express,NIPPON_EXPRESS,GLOBAL;
Northline,NORTHLINE,GLOBAL;
NYT SUPPLY CHAIN LOGISTICS Co. LTD,NYTLOGISTICS,GLOBAL;
Olive,SHOPOLIVE,GLOBAL;
ONTRAC,ONTRAC,GLOBAL;
Optima Courier,OPTIMACOURIER,GLOBAL;
Orangeconnex,ORANGECONNEX,GLOBAL;
OrangeDS (Orange Distribution Solutions Inc),ORANGE_DS,GLOBAL;
Ozeparts Shipping,OZEPARTS_SHIPPING,GLOBAL;
P2P TrakPak,P2P_TRC,GLOBAL;
PACK-UP,PACK_UP,GLOBAL;
Packeta,PACKETA,GLOBAL;
PACKFLEET,PACKFLEET,GLOBAL;
Packs,PACKS,GLOBAL;
Paikeda,PAIKEDA,GLOBAL;
Pakajo World,PAKAJO,GLOBAL;
Pandion,PANDION,GLOBAL;
PANDU,PANDU,GLOBAL;
Panther Order Number,PANTHER_ORDER_NUMBER,GLOBAL;
Parcel Right,PARCELRIGHT,GLOBAL;
Parcel To Post,PARCEL_2_POST,GLOBAL;
PARCELFORCE,PARCELFORCE,GLOBAL;
Parceljet,PARCELJET,GLOBAL;
PARCLL,PARCLL,GLOBAL;
Payo,PAYO,GLOBAL;
Pidge,PIDGE,GLOBAL;
PIL Logistics (China) Co.,PIL_LOGISTICS,GLOBAL;
Plycon Transportation Group,PLYCONGROUP,GLOBAL;
Post ONE,POSTONE,GLOBAL;
Posta Plus,POSTAPLUS,GLOBAL;
Poste Italiane Paccocelere,POSTE_ITALIANE_PACCOCELERE,GLOBAL;
Posten Norge (www.posten.no),POSTEN_NORGE,GLOBAL;
PostNL International,POSTNL_INTERNATIONAL,GLOBAL;
Postnord sweden,SWE_POSTNORD,GLOBAL;
PostPlus,POSTPLUS,GLOBAL;
PROFESSIONAL COURIERS,PROFESSIONAL_COURIERS,GLOBAL;
Professional Parcel Logistics,PPL,GLOBAL;
ProMed Delivery,PROMEDDELIVERY,GLOBAL;
PTT Kargo,PTT_KARGO,GLOBAL;
Purolator,PUROLATOR,GLOBAL;
QTrack,QTRACK,GLOBAL;
Quiqup,QUIQUP,GLOBAL;
Relay,RELAY,GLOBAL;
Rhenus Logistics,RHENUS_GROUP,GLOBAL;
Rich Mom,RICHMOM,GLOBAL;
Rodonaves,RODONAVES,GLOBAL;
Royalshipments,ROYALSHIPMENTS,GLOBAL;
Russian post,RUSSIAN_POST,GLOBAL;
SAGAWA,SAGAWA,GLOBAL;
Sber Logistics,SBERLOGISTICS_RU,GLOBAL;
Scotty,SCOTTY,GLOBAL;
Sendeo Kargo,SENDEO_KARGO,GLOBAL;
Sending Transporte Urgente y Comunicacion,SENDING,GLOBAL;
SENHONG INTERNATIONAL LOGISTICS,SHOWL,GLOBAL;
Servientrega,SERVIENTREGA,GLOBAL;
Setel Express,SETEL,GLOBAL;
SF Express,SF_EX,GLOBAL;
SF Express China,SF_EXPRESS_CN,GLOBAL;
Shadowfax,SHADOWFAX,GLOBAL;
Shenzhen 1st International Logistics(group)co,SHENZHEN,GLOBAL;
SHENZHEN HOTSIN CARGO INTL FORWARDING CO. LTD,HOTSIN_CARGO,GLOBAL;
Shenzhen Jinghuada Logistics Co.,KWT,GLOBAL;
Sherpa,SHERPA,GLOBAL;
Shipbob,SHIPBOB,GLOBAL;
Shiprocket X,SHIPROCKET,GLOBAL;
ShipX,SHIPX,GLOBAL;
SHIPXPRESS,SHIPXPRES,GLOBAL;
Shopee Express,SPX,GLOBAL;
Shopee Xpress,SPX_TH,GLOBAL;
ShunBang Express,SHUNBANG_EXPRESS,GLOBAL;
Shypmax,SHYPLITE,GLOBAL;
Sims Global,SIMSGLOBAL,GLOBAL;
SIODEMKA,SIODEMKA,GLOBAL;
SkyNet Worldwide Express,SKYNET_WORLDWIDE,GLOBAL;
SkyPostal,SKY_POSTAL,GLOBAL;
Slovenska poöta,SK_POSTA,GLOBAL;
SMARTCAT,SMARTCAT,GLOBAL;
SmartKargo,SMARTKARGO,GLOBAL;
Speedex,SPEEDEX,GLOBAL;
SPRINT PACK,SPRINT_PACK,GLOBAL;
SRT Transport,SRT_TRANSPORT,GLOBAL;
Startrack,STARTRACK,GLOBAL;
Startrack Express,STARTRACK_EXPRESS,GLOBAL;
Stat Overnight,STATOVERNIGHT,GLOBAL;
STO Express,CN_STO,GLOBAL;
Surat Kargo,SURAT_KARGO,GLOBAL;
SWE,SWE,GLOBAL;
Swiship,SWISHIP,GLOBAL;
Swiship IN,AMAZON_FBA_SWISHIP_IN,GLOBAL;
SWISS POST,SWISS_POST,GLOBAL;
T-cat,T_CAT,GLOBAL;
Taiwan Post,TW_TAIWAN_POST,GLOBAL;
TAQBIN Hong Kong,TAQBIN_HK,GLOBAL;
Taqbin SG,TAQBIN_SG,GLOBAL;
Testing Courier,TESTING_COURIER,GLOBAL;
Tforce Freight,TFORCE_FREIGHT,GLOBAL;
Thunder Express Australia,THUNDEREXPRESS,GLOBAL;
Tnt AU,TNT_AU,GLOBAL;
Tnt IT,TNT_IT,GLOBAL;
TNT Reference,TNT_REFR,GLOBAL;
TOLL IPEC,TOLL_IPEC,GLOBAL;
Toll Priority,TOLL_PRIORITY,GLOBAL;
Tomydoor,TOMYDOOR,GLOBAL;
Top Ideal Express,ESDEX,GLOBAL;
TP Logistic,THAIPARCELS,GLOBAL;
Trans2u,TRANS2U,GLOBAL;
TRANSMISSION,TRANSMISSION,GLOBAL;
Transport Ambientales,TANET,GLOBAL;
TransVirtual,TRANSVIRTUAL,GLOBAL;
Trunkrs,TRUNKRS,GLOBAL;
Trusk France,TRUSK,GLOBAL;
Tusk Logistics,TUSKLOGISTICS,GLOBAL;
TYP,TYP,GLOBAL;
U-ENVIOS,U_ENVIOS,GLOBAL;
UCS,UCS,GLOBAL;
United Delivery Service,UDS,GLOBAL;
United Parcel Service,UPS,GLOBAL;
Uniuni,UNIUNI,GLOBAL;
Uparcel,UPARCEL,GLOBAL;
Ups Checker,UPS_CHECKER,GLOBAL;
UPS Freight,UPS_FREIGHT,GLOBAL;
UPS Reference,UPS_REFERENCE,GLOBAL;
Us Apc,US_APC,GLOBAL;
ViaXpress,VIAXPRESS,GLOBAL;
We World Express,WEWORLDEXPRESS,GLOBAL;
Weee,WEEE,GLOBAL;
Welivery,WELIVERY,GLOBAL;
WeShip,WESHIP,GLOBAL;
Worldnet Logistics,WORLDNET,GLOBAL;
Xingyunyi Logistics,XYY,GLOBAL;
XPRESSBEES,XPRESSBEES,GLOBAL;
YAMATO,YAMATO,GLOBAL;
YiFan Express,YIFAN,GLOBAL;
Yodel,YODEL,GLOBAL;
Yodel Direct,YODEL_DIR,GLOBAL;
Yodel International,YODEL_INTNL,GLOBAL;
Yunhuipost,YUNHUIPOST,GLOBAL;
Yusen Logistics,YUSEN,GLOBAL;
Yycom,YYCOM,GLOBAL;
YYEXPRESS,YYEXPRESS,GLOBAL;
ZTO Express China,ZTO_DOMESTIC,GLOBAL;
Other,OTHER,GLOBAL;
Fasttrack,FASTRACK,ARG;
Grupo logistico Andreani,ANDREANI,ARG;
OCA Argentina,ARG_OCA,ARG;
ADSone,ADSONE,AUS;
Allied Express,ALLIEDEXPRESS,AUS;
Aramex Australia (formerly Fastway AU),ARAMEX_AU,AUS;
Australia Post,AU_AU_POST,AUS;
Blue Star,BLUESTAR,AUS;
Bonds Courier Service (bondscouriers.com.au),BONDSCOURIERS,AUS;
Border Express,BORDEREXPRESS,AUS;
Cope Sensitive Freight,COPE,AUS;
CouriersPlease (couriersplease.com.au),COURIERS_PLEASE,AUS;
Direct Couriers,DIRECTCOURIERS,AUS;
Direct Freight Express,DIRECTFREIGHT_AU,AUS;
Discount Post,EMEGA,AUS;
DTDC Australia,DTDC_AU,AUS;
Endeavour Delivery,ENDEAVOUR_DELIVERY,AUS;
Hunter Express,HUNTER_EXPRESS,AUS;
ICumulus,ICUMULUS,AUS;
Interparcel Australia,INTERPARCEL_AU,AUS;
Kinisi Transport Pty Ltd,KINISI,AUS;
Parcelpoint,PARCELPOINT,AUS;
PFL,PFLOGISTICS,AUS;
Sendle,SENDLE,AUS;
Shippit,SHIPPIT,AUS;
Star Track Express,STAR_TRACK_EXPRESS,AUS;
StarTrack (startrack.com.au),AUS_STARTRACK,AUS;
TFM Xpress,TFM,AUS;
TIG Freight,TIGFREIGHT,AUS;
UBI Smart Parcel,UBI_LOGISTICS,AUS;
VicTas Freight Express,VTFE,AUS;
XL Express,XL_EXPRESS,AUS;
Austrian Post,AUSTRIAN_POST_EXPRESS,AUT;
Austrian Post (Registered),AU_AUSTRIAN_POST,AUT;
DPD Austria,DPD_AT,AUT;
B2C courier Europe,B_TWO_C_EUROPE,BEL;
Landmark Global,LANDMARK_GLOBAL,BEL;
Mikropakket Belgium,MIKROPAKKET_BE,BEL;
BH Posta (www.posta.ba),BH_POSTA,BIH;
Correios Brazil,BRA_CORREIOS,BRA;
Directlog (www.directlog.com.br),DIRECTLOG,BRA;
Frete Rapido,FRETERAPIDO,BRA;
Intelipost (TMS for LATAM),INTELIPOST,BRA;
A1Post,A1POST,BGR;
Bulgarian Posts,BG_BULGARIAN_POST,BGR;
Cambodia Post,KHM_CAMBODIA_POST,KHM;
Roadbull Logistics,ROADRUNNER_FREIGHT,KHM;
American West,AWEST,CAN;
Canada Post,CA_CANADA_POST,CAN;
Chit Chats,CHITCHATS,CAN;
Courant Plus,COURANT_PLUS,CAN;
EShipper,ESHIPPER,CAN;
Estes Express Lines,GLOBAL_ESTES,CAN;
FleetOptics,FLEETOPTICSINC,CAN;
GLS Logistic Systems Canada Ltd./Dicom,DICOM,CAN;
GTA GSM,GTAGSM,CAN;
Intelcom,INTELCOM_CA,CAN;
Loomis Express,LOOMIS_EXPRESS,CAN;
MBW Courier Inc.,MBW,CAN;
Nationex courier,NATIONEX,CAN;
Obibox,OBIBOX,CAN;
Rivo (Air canada),AIR_CANADA_GLOBAL,CAN;
RPX Logistics,RPXLOGISTICS,CAN;
Stallion Express,STALLIONEXPRESS,CAN;
Ziing Final Mile Inc,ZIINGFINALMILE,CAN;
Blue Express,BLUEX,CHL;
Jawar,JAWAR,CHL;
OTS,OTSCHILE,CHL;
STARKEN couriers,STARKEN,CHL;
17 Post Service,CN_17POST,CHN;
ACS Worldwide Express,ACSWORLDWIDE,CHN;
AliExpress Standard Shipping,CAINIAO,CHN;
Anjun couriers,ANJUN,CHN;
ANSERX courier,ANSERX,CHN;
Aoyue,AOYUE,CHN;
BEL North Russia,BEL_RS,CHN;
Best Express,CN_BESTEXPRESS,CHN;
BoxC courier,CN_BOXC,CHN;
Captain Express International,CPEX,CHN;
CGS Express,CGS_EXPRESS,CHN;
China Post,CN_CHINA_POST_EMS,CHN;
Chukou1,CHUKOU1,CHN;
CJ Packet,CJPACKET,CHN;
Clevy Links,CLEVY_LINKS,CHN;
CND Express,CNDEXPRESS,CHN;
CNE Express,CNEXPS,CHN;
CometTech,COMET_TECH,CHN;
Cpacket couriers,CPACKET,CHN;
Cuckoo Express,CUCKOOEXPRESS,CHN;
DEX-I courier,DEX_I,CHN;
DIDADI Logistics tech,DIDADI,CHN;
DPE Express,DPE_EXPRESS,CHN;
DTD Express,DTD_EXPR,CHN;
EMPS Express,EMPS_CN,CHN;
Equick China,CN_EQUICK,CHN;
Eshipping,ESHIPPING,CHN;
Eshun international Logistic,ZES_EXPRESS,CHN;
FAR international,FAR_INTERNATIONAL,CHN;
FarGood,FARGOOD,CHN;
Fedex,FEDEX_CHINA,CHN;
Fulfillme,FULFILLME,CHN;
GANGBAO Supplychain,GANGBAO,CHN;
GESWL Express,GESWL,CHN;
Haidaibao,HDB,CHN;
Haidaibao (BOX),HDB_BOX,CHN;
Hua Han Logistics,HH_EXP,CHN;
HUAHANG EXPRESS,HUAHAN_EXPRESS,CHN;
Huodull,HUODULL,CHN;
HX Express,HX_EXPRESS,CHN;
IDEX courier,IDEXPRESS,CHN;
Intel-Valley Supply chain (ShenZhen) Co. Ltd,INTEL_VALLEY,CHN;
Jawar,JAWAR,CHN;
J-Net,J_NET,CHN;
Jindouyun Courier,JINDOUYUN,CHN;
Joom Logistics,JOOM_LOGIS,CHN;
Jumppoint,JUMPPOINT,CHN;
K1 Express,K1_EXPRESS,CHN;
Kua Yue Express,KY_EXPRESS,CHN;
Lalamove,LALAMOVE,CHN;
Leader,LEADER,CHN;
Lightning Monkey,SDH_SCM,CHN;
LM Parcel,LMPARCEL,CHN;
Logisters,LOGISTERS,CHN;
LTIAN EXP,LTIANEXP,CHN;
LTL COURIER,LTL,CHN;
Morelink,MORE_LINK,CHN;
Nanjing Woyuan,NANJINGWOYUAN,CHN;
One World Express,ONEWORLDEXPRESS,CHN;
Padtf,PADTF,CHN;
Pan-Asia International,PAN_ASIA,CHN;
PayPal Package,CN_PAYPAL_PACKAGE,CHN;
PFC Express,PFCEXPRESS,CHN;
Post56,CN_POST56,CHN;
Qingdao HKD International Logistics,HKD,CHN;
RETS express,ETS_EXPRESS,CHN;
Ruston,RUSTON,CHN;
SF Express (www.sf-express.com),CN_SF_EXPRESS,CHN;
SF International,SFB2C,CHN;
SFC,SFC_LOGISTICS,CHN;
SFC Service,SFCSERVICE,CHN;
Shanghai Aqrum Chemical Logistics Co.Ltd,DAJIN,CHN;
Shopline,SHOPLINE,CHN;
Sinotrans,SINOTRANS,CHN;
Speedaf Express,SPEEDAF,CHN;
STONE3PL,STONE3PL,CHN;
Sunyou Post,SYPOST,CHN;
Super Pac Line,SUPERPACKLINE,CHN;
TONDA GLOBAL,TARRIVE,CHN;
Tophatter Express,TOPHATTEREXPRESS,CHN;
TopYou,TOPYOU,CHN;
Ucexpress,UC_EXPRE,CHN;
VIWO IoT,VIWO,CHN;
WanbExpress,WANBEXPRESS,CHN;
Weaship,WEASHIP,CHN;
WeDo Logistics,CN_WEDO,CHN;
WinIt,WINIT,CHN;
Wise Express,WISE_EXPRESS,CHN;
WishPost,CN_WISHPOST,CHN;
Xmszm,XMSZM,CHN;
XQ Express,XQ_EXPRESS,CHN;
Yanwen Logistics,YANWEN,CHN;
YDH express,YDH_EXPRESS,CHN;
Yilian (Elian) Supply Chain,ELIAN_POST,CHN;
Yingnuo Logistics,YINGNUO_LOGISTICS,CHN;
YTO Express,YTO,CHN;
Yunant,YUNANT,CHN;
Yunda Express,CN_YUNDA,CHN;
YunExpress,YUNEXPRESS,CHN;
ZJS International,ZJS_EXPRESS,CHN;
ZTO Express,ZTO_EXPRESS,CHN;
ZYEX,ZYOU,CHN;
Coordinadora,COORDINADORA,COL;
GLS Croatia,GLS_CROTIA,HRV;
Hrvatska posta,HRV_HRVATSKA,HRV;
Overseas Express,OVERSE_EXP,HRV;
Cyprus Post,CYPRUS_POST_CYP,CYP;
Czech Post,CESKA_CZ,CZE;
GLS Czech Republic,GLS_CZ,CZE;
Danske Fragtaend,DANSKE_FRAGT,DNK;
Ostnord Denmark,POSTNORD_LOGISTICS_DK,DNK;
PostNord Logistics,POSTNORD_LOGISTICS,DNK;
Xpressen courier,XPRESSEN_DK,DNK;
Omniva,OMNIVA,EST;
Matkahuolto,MATKAHUOLTO,FIN;
Posti courier,POSTI,FIN;
Chronopost france (www.chronopost.fr),CHRONOPOST_FR,FRA;
Colis PrivÈ,COLIS_PRIVE,FRA;
Colissimo,FR_COLIS,FRA;
Cubyn,CUBYN,FRA;
DPD France,DPD_FR,FRA;
DPD France (formerly exapaq),FR_EXAPAQ,FRA;
Heppner France,HEPPNER_FR,FRA;
La Poste,LA_POSTE_SUIVI,FRA;
Swiss Universal Express,SWISS_UNIVERSAL_EXPRESS,FRA;
TNT France,TNT_FR,FRA;
VIR Transport,VIRTRANSPORT,FRA;
Hermes Germany,HERMES_DE,DEU;
AO Deutschland,AO_DEUTSCHLAND,DEU;
DPD Germany,DE_DPD_DELISTRACK,DEU;
Fiege Logistics,FIEGE,DEU;
Geis CZ,GEIS,DEU;
Gel Express Logistik,GEL_EXPRESS,DEU;
Go!Express and logistics,GENERAL_OVERNIGHT,DEU;
Heppner Internationale Spedition GmbH & Co.,HEPPNER,DEU;
Hermes Einrichtungs Service GmbH & Co. KG,HERMES_2MANN_HANDLING,DEU;
Innight Express Germany GmbH (nox NachtExpress),NOX_NACHTEXPRESS,DEU;
Liefery,LIEFERY,DEU;
NOX NightTimeExpress,NOX_NIGHT_TIME_EXPRESS,DEU;
PARCEL ONE,PARCELONE,DEU;
Pressio,PRESSIODE,DEU;
Raben Group,RABEN_GROUP,DEU;
Streck Transport,STRECK_TRANSPORT,DEU;
Swiship DE,SWISHIP_DE,DEU;
Urbify,URBIFY,DEU;
ACS Courier,ACS_GR,GRC;
Easy Mail,EASY_MAIL,GRC;
Geniki Taxydromiki,GENIKI_GR,GRC;
Packman,PACK_MAN,GRC;
Speed Couriers,SPEEDCOURIERS_GR,GRC;
CFL Logistics,CFL_LOGISTICS,HKG;
CJ Logistics International(Hong Kong),CJ_HK_INTERNATIONAL,HKG;
CL E-Logistics Solutions Limited,CLE_LOGISTICS,HKG;
Continental,CONTINENTAL,HKG;
Cosmetics Now,COSTMETICSNOW,HKG;
DealerSend,DEALERSEND,HKG;
DHL Global Mail Asia (www.dhl.com),DHL_GLOBAL_MAIL_ASIA,HKG;
DHL HonKong,DHL_HK,HKG;
DPD HongKong,DPD_HK,HKG;
DTDC express,DTDC_EXPRESS,HKG;
Globavend,GLOBAVEND,HKG;
Hongkong Post (www.hongkongpost.hk),HK_POST,HKG;
Janco Ecommerce,JANCO,HKG;
JS EXPRESS,JS_EXPRESS,HKG;
KEC courier,KEC,HKG;
Kerry eCommerce,KERRY_ECOMMERCE,HKG;
LHT Express,LHT_EXPRESS,HKG;
Logistic Worldwide Express (LWE Honkong),LOGISTICSWORLDWIDE_HK,HKG;
Mainway,MAINWAY,HKG;
Morning Express,MORNING_EXPRESS,HKG;
OkayParcel,OKAYPARCEL,HKG;
Omni Parcel,OMNIPARCEL,HKG;
PAL Express Limited,PALEXPRESS,HKG;
Pickupp,PICKUP,HKG;
Quantium,QUANTIUM,HKG;
SEKO Logistics,SEKOLOGISTICS,HKG;
Ship It Asia,SHIP_IT_ASIA,HKG;
Shopline,SHOPLINE,HKG;
Smooth Couriers,SMOOTH,HKG;
STEP FORWARD FREIGHT SERVICE CO LTD,STEPFORWARDFS,HKG;
DPD Hungary,DPD_HGRY,HUN;
EXPRESSONE,EXPRESSONE,HUN;
GLS Hungary,GLS_HUN,HUN;
AICS,ARIHANTCOURIER,IND;
Bombino Express Pvt,BOMBINOEXP,IND;
Delhivery India,IND_DELHIVERY,IND;
DELIVERYONTIME LOGISTICS PVT LTD,DELIVERYONTIME,IND;
DTDC India,DTDC_IN,IND;
Ecom Express,IND_ECOM,IND;
Ekart logistics (ekartlogistics.com),EKART,IND;
First Flight Couriers,IND_FIRSTFLIGHT,IND;
Gati-KWE,IND_GATI,IND;
GoJavas,IND_GOJAVAS,IND;
Grand Slam Express,GRANDSLAMEXPRESS,IND;
Holisol,HOLISOL,IND;
LexShip,LEXSHIP,IND;
OCS ANA Group,OCS,IND;
Parcelled.in,PARCELLED_IN,IND;
Pickrr,PICKRR,IND;
Safexpress,IND_SAFEEXPRESS,IND;
Scudex Express,SCUDEX_EXPRESS,IND;
Shree Anjani Courier,SHREE_ANJANI_COURIER,IND;
Shree Maruti Courier Services Pvt Ltd,SHREE_MARUTI,IND;
SHREE NANDAN COURIER,SHREENANDANCOURIER,IND;
SHREE TIRUPATI COURIER SERVICES PVT. LTD.,SHREETIRUPATI,IND;
Sky King,SKYKING,IND;
SPOTON Logistics Pvt Ltd,SPOTON,IND;
Trackon Couriers Pvt. Ltd,TRACKON,IND;
Xindus,XINDUS,IND;
Choir Express Indonesia,CHOIR_EXP,IDN;
INDOPAKET,INDOPAKET,IDN;
JX courier,JX,IDN;
KURASI,KURASI,IDN;
Ninja Van Indonesia,NINJAVAN_ID,IDN;
PT MGLOBAL LOGISTICS INDONESIA,MGLOBAL,IDN;
Red Carpet Logistics,RCL,IDN;
SAP EXPRESS,SAP_EXPRESS,IDN;
Sin Global Express,SIN_GLBL,IDN;
Tiki shipment,TIKI_ID,IDN;
Trans Kargo Internasional,TRANS_KARGO,IDN;
Wahana express (www.wahana.com),WAHANA_ID,IDN;
An Post,AN_POST,IRL;
DPD Ireland,DPD_IR,IRL;
Fastway Ireland,FASTWAY_IR,IRL;
Wiseloads,WISELOADS,IRL;
GC Express,GCX,ISR;
Israel Post,ISRAEL_POST,ISR;
Israel Post Domestic,ISR_POST_DOMESTIC,ISR;
BRT Bartolini(Parcel ID),BRT_IT_PARCELID,ITA;
BRT couriers Italy (www.brt.it),BRT_IT,ITA;
Arco Spedizioni SP,ARCO_SPEDIZIONI,ITA;
Blink,BLINKLASTMILE,ITA;
HR Parcel,HRPARCEL,ITA;
I Dika,I_DIKA,ITA;
InPost Italy,INPOST_IT,ITA;
LICCARDI EXPRESS COURIER,LICCARDI_EXPRESS,ITA;
Milkman courier,MILKMAN,ITA;
Poste italiane (www.poste.it),IT_POSTE_ITALIA,ITA;
SAILPOST,SAILPOST,ITA;
SDA Italy,SDA_IT,ITA;
Spedisci.online,SPEDISCI,ITA;
TNT-Click Italy,TNT_CLICK_IT,ITA;
Japan Post,JPN_JAPAN_POST,JPN;
KWE Global,KWE_GLOBAL,JPN;
MailPlus,MAIL_PLUS,JPN;
MailPlus (Japan),MAILPLUS_JPN,JPN;
Swiship JP,SWISHIP_JP,JPN;
Seino,SEINO,JPN;
Jersey Post,JERSEY_POST,JEY;
Cello Square,CELLO_SQUARE,KOR;
Croshot,CROSHOT,KOR;
Doora Logistics,DOORA,KOR;
Eparcel Korea,EPARCEL_KR,KOR;
Korea Post,KPOST,KOR;
Koreapost (www.koreapost.go.kr),KR_KOREA_POST,KOR;
Kyungdong Parcel,KYUNGDONG_PARCEL,KOR;
Lotte Global Logistics,LOTTE,KOR;
Rincos,RINCOS,KOR;
Rocket Parcel International,ROCKET_PARCEL,KOR;
ShipGate,SHIP_GATE,KOR;
SHIPTER,SHIPTER,KOR;
SRE Korea (www.srekorea.co.kr),SRE_KOREA,KOR;
Tolos courier,TOLOS,KOR;
Lao Post,LAO_POST,LAO;
CDEK courier,CDEK,LVA;
Latvijas Pasts,LATVIJAS_PASTS,LVA;
Venipak,VENIPAK,LTU;
ABX Express,ABXEXPRESS_MY,MYS;
Airpak Express,MYS_AIRPAK,MYS;
City-Link Express,CITYLINK_MY,MYS;
CJ International malaysia,CJ_INT_MY,MYS;
CollectCo,COLLECTCO,MYS;
Easyparcel,EASYPARCEL,MYS;
FMX,FMX,MYS;
GDEX courier,MYS_GDEX,MYS;
J&T EXPRESS MALAYSIA,JTEXPRESS,MYS;
JINSUNG TRADING,JINSUNG,MYS;
Jocom,JOCOM,MYS;
Kangaroo Worldwide Express,KANGAROO_MY,MYS;
Line Clear Express & Logistics Sdn Bhd,LINE,MYS;
M Xpress Sdn Bhd,M_XPRESS,MYS;
Malaysia Post,MYS_MYS_POST,MYS;
Matdespatch,MATDESPATCH,MYS;
Nationwide Express Courier Services Bhd (www.nationwide.com.my),NATIONWIDE_MY,MYS;
Ninja Van (www.ninjavan.co),NINJAVAN_MY,MYS;
PICK UPP,PICKUPP_MYS,MYS;
Sendy Express,SENDY,MYS;
Skynet Malaysia,MYS_SKYNET,MYS;
WePost Sdn Bhd,WEPOST,MYS;
Correos Mexico,CORREOS_DE_MEXICO,MEX;
DOMINO,DOMINO,MEX;
Estafeta (www.estafeta.com),MEX_ESTAFETA,MEX;
Grupo ampm,GRUPO,MEX;
Hound Express,HOUNDEXPRESS,MEX;
mexico senda express,MEX_SENDA,MEX;
Paquetexpress,PAQUETEXPRESS,MEX;
Redpack,MEX_REDPACK,MEX;
Brouwer Transport en Logistiek,BROUWER_TRANSPORT,NLD;
DHL Netherland,NLD_DHL,NLD;
Fiege Netherlands,FIEGE_NL,NLD;
GLS Netherland,NLD_GLS,NLD;
Packaly,PACKALY,NLD;
Paper Express,PAPER_EXPRESS,NLD;
PostNL International 3S,POSTNL_INTL_3S,NLD;
Castle Parcels,CASTLEPARCELS,NZL;
Fastway New Zealand,FASTWAY_NZ,NZL;
Interparcel New Zealand,INTERPARCEL_NZ,NZL;
Mainfreight,MAINFREIGHT,NZL;
New Zealand Post,NZ_NZ_POST,NZL;
Toll New Zealand,TOLL_NZ,NZL;
NIpost (www.nipost.gov.ng),NIPOST_NG,NGA;
Helthjem,HELTHJEM,NOR;
Asyad Express,ASYADEXPRESS,OMN;
Forrun Pvt Ltd (Arpatech Venture),FORRUN,PAK;
TCS courier,TCS,PAK;
Multientrega,MULTIENTREGAPANAMA,PAN;
AEX Group,AEX,PRY;
2GO Courier,TWO_GO,PHL;
Jam Express Philippines,PHL_JAMEXPRESS,PHL;
RAF Philippines,RAF_PH,PHL;
Xpost.ph,XPOST,PHL;
DHL Poland,DHL_PL,POL;
DPD Poland,DPD_POLAND,POL;
FedExÆ Poland Domestic,FEDEX_POLAND,POL;
InPost Paczkomaty,INPOST_PACZKOMATY,POL;
Parcelstars,PARCELSTARS,POL;
Poczta Polska (www.poczta-polska.pl),PL_POCZTA_POLSKA,POL;
Adicional Logistics,ADICIONAL,PRT;
Bneed courier,BNEED,PRT;
Carriers courier,CARRIERS,PRT;
Chronopost Portugal,PRT_CHRONOPOST,PRT;
CTT Portugal,PRT_CTT,PRT;
Delnext,DELNEXT,PRT;
DPD Portugal,DPD_PRT,PRT;
DPD Romania,DPD_RO,ROU;
GLS Romania,GLS_ROMANIA,ROU;
Post Roman (www.posta-romana.ro),POSTA_RO,ROU;
Boxberry courier,BOX_BERRY,RUS;
CSE courier,CSE,RUS;
DHL Parcel Russia,DHL_PARCEL_RU,RUS;
DobroPost,DOBROPOST,RUS;
DPD Russia,DPD_RU,RUS;
Expresssale,EXPRESSSALE,RUS;
GBS-Broker,GBS_BROKER,RUS;
Pony express,PONY_EXPRESS,RUS;
ShopfansRU LLC,SHOPFANS,RUS;
Saudi Post,SAU_SAUDI_POST,SAU;
SkyExpress Internationals,SKYEXPRESSINTERNATIONAL,SAU;
SMSA Express,SMSA_EXPRESS,SAU;
Thabit Logistics,THABIT_LOGISTICS,SAU;
Zajil Express Company,ZAJIL_EXPRESS,SAU;
Posta Serbia,POST_SERBIA,SRB;
Cloudwish Asia,CLOUDWISH_ASIA,SGP;
Detrack,SG_DETRACK,SGP;
Fonsen Logistics,FONSEN,SGP;
J&T Express Singapore,SIMPLYPOST,SGP;
Janio Asia,JANIO,SGP;
Jayon Express (JEX),IND_JAYONEXPRESS,SGP;
Jet-Ship Worldwide,JET_SHIP,SGP;
KGM Hub,KGMHUB,SGP;
Legion Express,LEGION_EXPRESS,SGP;
Nhans Solutions,NHANS_SOLUTIONS,SGP;
Ninja van Singapore,NINJAVAN_SG,SGP;
Parcel Post Singapore,PARCELPOST_SG,SGP;
Park N Parcel,PARKNPARCEL,SGP;
PICK UPP (Singapore),PICKUPP_SGP,SGP;
Qxpress,SG_QXPRESS,SGP;
RaidereX,RAIDEREX,SGP;
Red Carpet Logistics,ROADBULL,SGP;
RZY Express,RZYEXPRESS,SGP;
Singapore Post,SG_SG_POST,SGP;
Singapore Speedpost,SG_SPEEDPOST,SGP;
TCK Express,TCK_EXPRESS,SGP;
Urbanfox,COUREX,SGP;
GLS General Logistics Systems Slovakia s.r.o.,GLS_SLOV,SVK;
EXPRESSONE,EXPRESSONE_SV,SVN;
GLS Slovenia,GLS_SLOVEN,SVN;
Post of Slovenia,POST_SLOVENIA,SVN;
Courier IT,ZA_COURIERIT,ZAF;
Dawn Wing,DAWN_WING,ZAF;
DPE South Africa,DPE_SOUTH_AFRC,ZAF;
Internet Express,INTEXPRESS,ZAF;
MDS Collivery Pty (Ltd),COLLIVERY,ZAF;
RAM courier,RAM,ZAF;
Skynet World Wide Express South Africa,SKYNET_ZA,ZAF;
South African Post Office,SOUTH_AFRICAN_POST_OFFICE,ZAF;
Specialised Freight,ZA_SPECIALISED_FREIGHT,ZAF;
The Courier Guy,THECOURIERGUY,ZAF;
ASIGNA courier,ASIGNA,ESP;
ASM(GLS Spain),ESP_ASM,ESP;
Cacesa,CACESA,ESP;
CBL Logistica,CBL_LOGISTICA,ESP;
Correos Express,CORREOS_EXPRESS,ESP;
DHL parcel Spain(www.dhl.com),DHL_PARCEL_ES,ESP;
DHL Spain(www.dhl.com),DHL_ES,ESP;
DIR,DIRMENSAJERIA,ESP;
ECOSCOOTING,ECOSCOOTING,ESP;
Envialia,ESP_ENVIALIA,ESP;
Envialia Reference,ENVIALIA_REFERENCE,ESP;
MRW,MRW,ESP;
MRW spain,ESP_MRW,ESP;
NACEX Spain,NACEX_ES,ESP;
Packlink,ESP_PACKLINK,ESP;
Redur Spain,ESP_REDUR,ESP;
SEUR International,PRT_INT_SEUR,ESP;
SEUR portugal,PRT_SEUR,ESP;
Spring GDS,SPRING_GDS,ESP;
SZENDEX,SZENDEX,ESP;
TDN,TDN,ESP;
THT Netherland,TNT_NL,ESP;
TIPSA courier,TIPSA,ESP;
TNT Express,TNT,ESP;
TNT global,GLOBAL_TNT,ESP;
Tourline,TOURLINE,ESP;
Xpo Logistics,XPO_ES,ESP;
Zeleris,ZELERIS,ESP;
Bring,BRING,SWE;
DB Schenker (www.dbschenker.com),DBSCHENKER_SE,SWE;
DB Schenker Sweden,DBSCHENKER_SV,SWE;
Early Bird,EARLYBIRD,SWE;
Urb-it,URB_IT,SWE;
Asendia HonKong,ASENDIA_HK,CHE;
Planzer Group,PLANZER,CHE;
ViaEurope,VIAEUROPE,CHE;
Cnwangtong,CNWANGTONG,TWN;
CTC Express,CTC_EXPRESS,TWN;
Dimerco Express Group,DIMERCO,TWN;
HCT LOGISTICS CO.LTD.,HCT_LOGISTICS,TWN;
Kerry TJ Logistics,KERRYTJ,TWN;
PRESIDENT TRANSNET CORP,PRESIDENT_TRANS,TWN;
Tai Wan Global Business,GLOBAL_EXPRESS,TWN;
Alphafast (www.alphafast.com),ALPHAFAST,THA;
CJ Korea Express,CJ_KR,THA;
Fastrak Services,FASTRK_SERV,THA;
Flash Express,FLASHEXPRESS,THA;
Nim Express,NIM_EXPRESS,THA;
Ninja van Thai,NINJAVAN_THAI,THA;
Sendit,SENDIT,THA;
SKYBOX,SKYBOX,THA;
Thailand Post (www.thailandpost.co.th),THA_THAILAND_POST,THA;
ASE KARGO,ASE,TUR;
Barsan Global Lojistik,BARSAN,TUR;
CDEK TR,CDEK_TR,TUR;
Navlungo,NAVLUNGO,TUR;
PTS courier,PTS,TUR;
PTT Post,PTT_POST,TUR;
ShipEntegra,SHIPENTEGRA,TUR;
Yurtici Kargo,YURTICI_KARGO,TUR;
Nova Poshta (International),NOVA_POSHTA_INT,UKR;
Nova Poshta (novaposhta.ua),NOVA_POSHTA,UKR;
UkrPoshta,POSTA_UKR,UKR;
Beone Logistics,IBEONE,ARE;
One click delivery services,ONECLICK,ARE;
SKYNET UAE,SKYNET_UAE,ARE;
Team Express Service LLC,TEAMEXPRESSLLC,ARE;
Amazon Shipping,AMAZON,GBR;
AO Logistics,AO_COURIER,GBR;
APC overnight (apc-overnight.com),APC_OVERNIGHT,GBR;
APC Overnight Consignment,APC_OVERNIGHT_CONNUM,GBR;
APG eCommerce Solutions,APG,GBR;
ARK Logistics,ARK_LOGISTICS,GBR;
Arrow XL,GB_ARROW,GBR;
Asendia UK,ASENDIA_UK,GBR;
BirdSystem,BIRDSYSTEM,GBR;
Bluecare Express Ltd,BLUECARE,GBR;
CAE Delivers,CAE_DELIVERS,GBR;
DAI Post,DAIGLOBALTRACK,GBR;
Deltec Courier,DELTEC_UK,GBR;
Diamond Eurogistics Limited,DIAMOND_EUROGISTICS,GBR;
DMSMatrix,DMS_MATRIX,GBR;
DPD Local,DPD_LOCAL,GBR;
DPD Local reference,DPD_LOCAL_REF,GBR;
EU Fleet Solutions,EU_FLEET_SOLUTIONS,GBR;
FedExÆ UK,FEDEX_UK,GBR;
Furdeco,FURDECO,GBR;
GBA Services Ltd,GBA,GBR;
GEM Worldwide,GEMWORLDWIDE,GBR;
HermesWorld UK,HERMES,GBR;
Home Delivery Solutions Ltd,HOME_DELIVERY_SOLUTIONS,GBR;
Interparcel UK,INTERPARCEL_UK,GBR;
MyHermes UK,MYHERMES,GBR;
National Sameday,NATIONAL_SAMEDAY,GBR;
Norsk Global,GB_NORSK,GBR;
OCS WORLDWIDE,OCS_WORLDWIDE,GBR;
Palletways,PALLETWAYS,GBR;
Panther,GB_PANTHER,GBR;
Panther Reference,PANTHER_REFERENCE,GBR;
Parcel2Go,PARCEL2GO,GBR;
Parcelink Logistics,PARCELINKLOGISTICS,GBR;
Rhenus Logistics UK,RHENUS_UK,GBR;
Royal Mail,ROYAL_MAIL,GBR;
RPD2man Deliveries,RPD2MAN,GBR;
Skynet UK,SKYNET_UK,GBR;
Swiship UK,AMAZON_FBA_SWISHIP,GBR;
TDG ñ The Delivery Group,THEDELIVERYGROUP,GBR;
The Pallet Network,PALLET_NETWORK,GBR;
TNT UK Limited (www.tnt.com),TNT_UK,GBR;
TNT UK Reference,TNT_UK_REFR,GBR;
Tuffnells Parcels Express,GB_TUFFNELLS,GBR;
Tuffnells Parcels Express- Reference,TUFFNELLS_REFERENCE,GBR;
UK mail (ukmail.com),UK_UK_MAIL,GBR;
Whistl,WHISTL,GBR;
WnDirect,WNDIRECT,GBR;
XDP Express,UK_XDP,GBR;
XDP Express Reference,XDP_UK_REFERENCE,GBR;
Xpert Delivery,XPERT_DELIVERY,GBR;
Yodel (www.yodel.co.uk),UK_YODEL,GBR;
A Duie Pyle,ADUIEPYLE,USA;
AAA Cooper,AAA_COOPER,USA;
ABF Freight,GLOBAL_ABF,USA;
Aeronet couriers,AERONET,USA;
Agility,AGILITY,USA;
Always Express,ALWAYS_EXPRESS,USA;
ANICAM BOX EXPRESS,ANICAM_BOX,USA;
Aquiline,AQUILINE,USA;
Associate Global Systems,AGSYSTEMS,USA;
Bond courier,BOND,USA;
Brauns Express,BRAUNSEXPRESS,USA;
Bringer Parcel Services,BRINGER,USA;
Champion Logistics,CHAMPION_LOGISTICS,USA;
Con-way Freight,CON_WAY,USA;
Dayton Freight,DAYTON_FREIGHT,USA;
Destiny Transportation,DESTINY,USA;
DHL Supply Chain APAC,DHL_SUPPLY_CHAIN,USA;
Echo courier,ECHO,USA;
EPost Global,EPST_GLBL,USA;
FDSEXPRESS,FDSEXPRESS,USA;
Fedex,FEDEX,USA;
FedEx Cross Border,FEDEX_CROSSBORDER,USA;
FedEx International MailService,FEDEX_INTL_MLSERV,USA;
FirstMile,FIRSTMILE,USA;
Freightquote by C.H. Robinson,FREIGHTQUOTE,USA;
Fulfilla,FULFILLA,USA;
GLS USA,GLS_US,USA;
GlobalTranz,GLOBALTRANZ,USA;
GSI EXPRESS,GSI_EXPRESS,USA;
GSO(GLS-USA),GSO,USA;
Hipshipper,HIPSHIPPER,USA;
I Parcel,GLOBAL_IPARCEL,USA;
Innovel courier,DESCARTES,USA;
IOR Direct Solutions,IORDIRECT,USA;
LaserShip,US_LASERSHIP,USA;
Leman,LEMAN,USA;
Lone Star Overnight,LONESTAR,USA;
Maergo,MAERGO,USA;
MailAmericas,MAILAMERICAS,USA;
Newegg Express,NEWEGGEXPRESS,USA;
Oakh Harbour Freight Lines,OAKH,USA;
Old Dominion Freight Line,US_OLD_DOMINION,USA;
OSM Worldwide,OSM_WORLDWIDE,USA;
PIGGYSHIP,PIGGYSHIP,USA;
Pilot Freight Services,PILOT_FREIGHT,USA;
Pitney Bowes,PITNEY_BOWES,USA;
PITT OHIO,PITTOHIO,USA;
Qwintry Logistics,QWINTRY,USA;
RL Carriers,RL_US,USA;
RPM,RPM,USA;
Saia LTL Freight,SAIA_FREIGHT,USA;
ShipGlobal,SHIPGLOBAL_US,USA;
Southwestern Motor Transport. Inc,SMTL,USA;
Southeastern Freight Lines,SEFL,USA;
Spee-Dee Delivery,SPEEDEE,USA;
SpeedX,SPEEDX,USA;
Sutton Transport,SUTTON,USA;
Tazmanian Freight Systems,TAZMANIAN_FREIGHT,USA;
TForce Final Mile,TFORCE_FINALMILE,USA;
Transpak Inc.,TRANSPAK,USA;
TRUMPCARD LLC,TRUMPCARD,USA;
United States Postal Service,USPS,USA;
UPS Mail Innovations,UPS_MAIL_INNOVATIONS,USA;
USF Reddaway,USF_REDDAWAY,USA;
UShip courier,USHIP,USA;
Vesyl,VESYL,USA;
Westgate Global,WESTGATE_GL,USA;
Wineshipping,WINESHIPPING,USA;
Wizmo,WIZMO,USA;
XGS,XGS,USA;
XPO logistics,XPO_LOGISTICS,USA;
Yakit courier,YAKIT,USA;
YouParcel,YOUPARCEL,USA;
YRC courier,US_YRC,USA;
Zinc courier,ZINC,USA;
Correo Uruguayo,CORREO_UY,URY;
Zoom,ZOOM_RED,VEN;
J&T Express Vietnam,JTEXPRESS_VN,VNM;
Kerry Express (Vietnam) Co Ltd,KERRYTTC_VN,VNM;
Nhat Tin Logistics,NTLOGISTICS_VN,VNM;
Ninjavan Vietnam,NINJAVAN_VN,VNM;
SG LINK,SGLINK,VNM;
Vietnam Post,VNM_VIETNAM_POST,VNM;
ViettelPost,VNM_VIETTELPOST,VNM;
CSV;
}
