<?php
namespace Database\Seeders;

use Database\Seeders\zencart\AddressBookTableSeeder;
use Database\Seeders\zencart\AddressFormatTableSeeder;
use Database\Seeders\zencart\AdminMenusTableSeeder;
use Database\Seeders\zencart\AdminPagesTableSeeder;
use Database\Seeders\zencart\AdminPagesToProfilesTableSeeder;
use Database\Seeders\zencart\AdminProfilesTableSeeder;
use Database\Seeders\zencart\AdminTableSeeder;
use Database\Seeders\zencart\BannersHistoryTableSeeder;
use Database\Seeders\zencart\BannersTableSeeder;
use Database\Seeders\zencart\CategoriesDescriptionTableSeeder;
use Database\Seeders\zencart\CategoriesTableSeeder;
use Database\Seeders\zencart\ConfigurationGroupTableSeeder;
use Database\Seeders\zencart\ConfigurationTableSeeder;
use Database\Seeders\zencart\CounterHistoryTableSeeder;
use Database\Seeders\zencart\CounterTableSeeder;
use Database\Seeders\zencart\CountProductViewsTableSeeder;
use Database\Seeders\zencart\CountriesTableSeeder;
use Database\Seeders\zencart\CurrenciesTableSeeder;
use Database\Seeders\zencart\CustomersInfoTableSeeder;
use Database\Seeders\zencart\CustomersTableSeeder;
use Database\Seeders\zencart\EzpagesContentTableSeeder;
use Database\Seeders\zencart\EzpagesTableSeeder;
use Database\Seeders\zencart\FeaturedTableSeeder;
use Database\Seeders\zencart\GeoZonesTableSeeder;
use Database\Seeders\zencart\GetTermsToFilterTableSeeder;
use Database\Seeders\zencart\GroupPricingTableSeeder;
use Database\Seeders\zencart\LanguagesTableSeeder;
use Database\Seeders\zencart\LayoutBoxesTableSeeder;
use Database\Seeders\zencart\ManufacturersInfoTableSeeder;
use Database\Seeders\zencart\ManufacturersTableSeeder;
use Database\Seeders\zencart\MediaClipsTableSeeder;
use Database\Seeders\zencart\MediaManagerTableSeeder;
use Database\Seeders\zencart\MediaToProductsTableSeeder;
use Database\Seeders\zencart\MediaTypesTableSeeder;
use Database\Seeders\zencart\MusicGenreTableSeeder;
use Database\Seeders\zencart\OrdersStatusTableSeeder;
use Database\Seeders\zencart\PaypalPaymentStatusTableSeeder;
use Database\Seeders\zencart\ProductMusicExtraTableSeeder;
use Database\Seeders\zencart\ProductsAttributesDownloadTableSeeder;
use Database\Seeders\zencart\ProductsAttributesTableSeeder;
use Database\Seeders\zencart\ProductsDescriptionTableSeeder;
use Database\Seeders\zencart\ProductsDiscountQuantityTableSeeder;
use Database\Seeders\zencart\ProductsOptionsTableSeeder;
use Database\Seeders\zencart\ProductsOptionsTypesTableSeeder;
use Database\Seeders\zencart\ProductsOptionsValuesTableSeeder;
use Database\Seeders\zencart\ProductsOptionsValuesToProductsOptionsTableSeeder;
use Database\Seeders\zencart\ProductsTableSeeder;
use Database\Seeders\zencart\ProductsToCategoriesTableSeeder;
use Database\Seeders\zencart\ProductTypeLayoutTableSeeder;
use Database\Seeders\zencart\ProductTypesTableSeeder;
use Database\Seeders\zencart\ProductTypesToCategoryTableSeeder;
use Database\Seeders\zencart\ProjectVersionHistoryTableSeeder;
use Database\Seeders\zencart\ProjectVersionTableSeeder;
use Database\Seeders\zencart\QueryBuilderTableSeeder;
use Database\Seeders\zencart\RecordArtistsInfoTableSeeder;
use Database\Seeders\zencart\RecordArtistsTableSeeder;
use Database\Seeders\zencart\RecordCompanyInfoTableSeeder;
use Database\Seeders\zencart\RecordCompanyTableSeeder;
use Database\Seeders\zencart\ReviewsDescriptionTableSeeder;
use Database\Seeders\zencart\ReviewsTableSeeder;
use Database\Seeders\zencart\SalemakerSalesTableSeeder;
use Database\Seeders\zencart\SpecialsTableSeeder;
use Database\Seeders\zencart\TaxClassTableSeeder;
use Database\Seeders\zencart\TaxRatesTableSeeder;
use Database\Seeders\zencart\TemplateSelectTableSeeder;
use Database\Seeders\zencart\ZonesTableSeeder;
use Database\Seeders\zencart\ZonesToGeoZonesTableSeeder;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $this->call(AddressBookTableSeeder::class);
        $this->call(AddressFormatTableSeeder::class);
        $this->call(AdminTableSeeder::class);
        $this->call(AdminMenusTableSeeder::class);
        $this->call(AdminPagesTableSeeder::class);
        $this->call(AdminPagesToProfilesTableSeeder::class);
        $this->call(AdminProfilesTableSeeder::class);
        $this->call(BannersTableSeeder::class);
        $this->call(BannersHistoryTableSeeder::class);
        $this->call(CategoriesTableSeeder::class);
        $this->call(CategoriesDescriptionTableSeeder::class);
        $this->call(ConfigurationTableSeeder::class);
        $this->call(ConfigurationGroupTableSeeder::class);
        $this->call(CountProductViewsTableSeeder::class);
        $this->call(CounterTableSeeder::class);
        $this->call(CounterHistoryTableSeeder::class);
        $this->call(CountriesTableSeeder::class);
        $this->call(CurrenciesTableSeeder::class);
        $this->call(CustomersTableSeeder::class);
        $this->call(CustomersInfoTableSeeder::class);
        $this->call(EzpagesTableSeeder::class);
        $this->call(EzpagesContentTableSeeder::class);
        $this->call(FeaturedTableSeeder::class);
        $this->call(GeoZonesTableSeeder::class);
        $this->call(GetTermsToFilterTableSeeder::class);
        $this->call(GroupPricingTableSeeder::class);
        $this->call(LanguagesTableSeeder::class);
        $this->call(LayoutBoxesTableSeeder::class);
        $this->call(ManufacturersTableSeeder::class);
        $this->call(ManufacturersInfoTableSeeder::class);
        $this->call(MediaClipsTableSeeder::class);
        $this->call(MediaManagerTableSeeder::class);
        $this->call(MediaToProductsTableSeeder::class);
        $this->call(MediaTypesTableSeeder::class);
        $this->call(MusicGenreTableSeeder::class);
        $this->call(OrdersStatusTableSeeder::class);
        $this->call(PaypalPaymentStatusTableSeeder::class);
        $this->call(ProductMusicExtraTableSeeder::class);
        $this->call(ProductTypeLayoutTableSeeder::class);
        $this->call(ProductTypesTableSeeder::class);
        $this->call(ProductTypesToCategoryTableSeeder::class);
        $this->call(ProductsTableSeeder::class);
        $this->call(ProductsAttributesTableSeeder::class);
        $this->call(ProductsAttributesDownloadTableSeeder::class);
        $this->call(ProductsDescriptionTableSeeder::class);
        $this->call(ProductsDiscountQuantityTableSeeder::class);
        $this->call(ProductsOptionsTableSeeder::class);
        $this->call(ProductsOptionsTypesTableSeeder::class);
        $this->call(ProductsOptionsValuesTableSeeder::class);
        $this->call(ProductsOptionsValuesToProductsOptionsTableSeeder::class);
        $this->call(ProductsToCategoriesTableSeeder::class);
        $this->call(ProjectVersionTableSeeder::class);
        $this->call(ProjectVersionHistoryTableSeeder::class);
        $this->call(QueryBuilderTableSeeder::class);
        $this->call(RecordArtistsTableSeeder::class);
        $this->call(RecordArtistsInfoTableSeeder::class);
        $this->call(RecordCompanyTableSeeder::class);
        $this->call(RecordCompanyInfoTableSeeder::class);
        $this->call(ReviewsTableSeeder::class);
        $this->call(ReviewsDescriptionTableSeeder::class);
        $this->call(SalemakerSalesTableSeeder::class);
        $this->call(SpecialsTableSeeder::class);
        $this->call(TaxClassTableSeeder::class);
        $this->call(TaxRatesTableSeeder::class);
        $this->call(TemplateSelectTableSeeder::class);
        $this->call(ZonesTableSeeder::class);
        $this->call(ZonesToGeoZonesTableSeeder::class);
        $this->call(\Database\Seeders\laravel\RoleSeeder::class);
        $this->call(\Database\Seeders\laravel\UserSeeder::class);
        $this->call(\Database\Seeders\laravel\DeveloperSeeder::class);

    }
}
