#
# * Country/Zones Zen Cart SQL Load for MySQL databases
# * @package Installer
# * @access private
# * @copyright Copyright 2003-2013 Zen Cart Development Team
# * @copyright Portions Copyright 2003 osCommerce
# * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
# * @version GIT: $Id: Author: DrByte  Wed Jul 18 16:51:48 2012 -0400 Modified in v1.5.1 $
#

## Specific to LATIN1 character set

INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function) VALUES ('Convert currencies for Text emails', 'CURRENCIES_TRANSLATIONS', '', 'What currency conversions do you need for Text emails?<br />Example = &amp;pound;,&pound;:&amp;euro;,&euro;', 12, 120, NULL, '2003-11-21 00:00:00', NULL, 'zen_cfg_textarea_small(');

INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (240,'AX','ALA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (1,'AF','AFG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (2,'AL','ALB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (3,'DZ','DZA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (4,'AS','ASM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (5,'AD','AND','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (6,'AO','AGO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (7,'AI','AIA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (8,'AQ','ATA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (9,'AG','ATG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (10,'AR','ARG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (11,'AM','ARM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (12,'AW','ABW','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (13,'AU','AUS','7');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (14,'AT','AUT','5');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (15,'AZ','AZE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (16,'BS','BHS','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (17,'BH','BHR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (18,'BD','BGD','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (19,'BB','BRB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (20,'BY','BLR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (21,'BE','BEL','5');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (22,'BZ','BLZ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (23,'BJ','BEN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (24,'BM','BMU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (25,'BT','BTN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (26,'BO','BOL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (27,'BA','BIH','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (28,'BW','BWA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (29,'BV','BVT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (30,'BR','BRA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (31,'IO','IOT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (32,'BN','BRN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (33,'BG','BGR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (34,'BF','BFA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (35,'BI','BDI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (36,'KH','KHM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (37,'CM','CMR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (38,'CA','CAN','2');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (39,'CV','CPV','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (40,'KY','CYM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (41,'CF','CAF','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (42,'TD','TCD','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (43,'CL','CHL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (44,'CN','CHN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (45,'CX','CXR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (46,'CC','CCK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (47,'CO','COL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (48,'KM','COM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (49,'CG','COG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (50,'CK','COK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (51,'CR','CRI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (52,'CI','CIV','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (53,'HR','HRV','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (54,'CU','CUB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (55,'CY','CYP','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (56,'CZ','CZE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (57,'DK','DNK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (58,'DJ','DJI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (59,'DM','DMA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (60,'DO','DOM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (61,'TL','TLS','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (62,'EC','ECU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (63,'EG','EGY','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (64,'SV','SLV','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (65,'GQ','GNQ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (66,'ER','ERI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (67,'EE','EST','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (68,'ET','ETH','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (69,'FK','FLK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (70,'FO','FRO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (71,'FJ','FJI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (72,'FI','FIN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (73,'FR','FRA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (75,'GF','GUF','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (76,'PF','PYF','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (77,'TF','ATF','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (78,'GA','GAB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (79,'GM','GMB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (80,'GE','GEO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (81,'DE','DEU','5');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (82,'GH','GHA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (83,'GI','GIB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (84,'GR','GRC','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (85,'GL','GRL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (86,'GD','GRD','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (87,'GP','GLP','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (88,'GU','GUM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (89,'GT','GTM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (90,'GN','GIN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (91,'GW','GNB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (92,'GY','GUY','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (93,'HT','HTI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (94,'HM','HMD','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (95,'HN','HND','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (96,'HK','HKG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (97,'HU','HUN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (98,'IS','ISL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (99,'IN','IND','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (100,'ID','IDN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (101,'IR','IRN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (102,'IQ','IRQ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (103,'IE','IRL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (104,'IL','ISR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (105,'IT','ITA','5');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (106,'JM','JAM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (107,'JP','JPN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (108,'JO','JOR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (109,'KZ','KAZ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (110,'KE','KEN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (111,'KI','KIR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (112,'KP','PRK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (113,'KR','KOR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (114,'KW','KWT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (115,'KG','KGZ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (116,'LA','LAO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (117,'LV','LVA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (118,'LB','LBN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (119,'LS','LSO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (120,'LR','LBR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (121,'LY','LBY','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (122,'LI','LIE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (123,'LT','LTU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (124,'LU','LUX','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (125,'MO','MAC','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (126,'MK','MKD','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (127,'MG','MDG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (128,'MW','MWI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (129,'MY','MYS','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (130,'MV','MDV','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (131,'ML','MLI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (132,'MT','MLT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (133,'MH','MHL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (134,'MQ','MTQ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (135,'MR','MRT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (136,'MU','MUS','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (137,'YT','MYT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (138,'MX','MEX','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (139,'FM','FSM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (140,'MD','MDA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (141,'MC','MCO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (142,'MN','MNG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (143,'MS','MSR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (144,'MA','MAR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (145,'MZ','MOZ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (146,'MM','MMR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (147,'NA','NAM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (148,'NR','NRU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (149,'NP','NPL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (150,'NL','NLD','5');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (151,'BQ','BES','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (152,'NC','NCL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (153,'NZ','NZL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (154,'NI','NIC','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (155,'NE','NER','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (156,'NG','NGA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (157,'NU','NIU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (158,'NF','NFK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (159,'MP','MNP','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (160,'NO','NOR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (161,'OM','OMN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (162,'PK','PAK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (163,'PW','PLW','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (164,'PA','PAN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (165,'PG','PNG','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (166,'PY','PRY','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (167,'PE','PER','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (168,'PH','PHL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (169,'PN','PCN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (170,'PL','POL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (171,'PT','PRT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (172,'PR','PRI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (173,'QA','QAT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (174,'RE','REU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (175,'RO','ROU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (176,'RU','RUS','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (177,'RW','RWA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (178,'KN','KNA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (179,'LC','LCA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (180,'VC','VCT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (181,'WS','WSM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (182,'SM','SMR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (183,'ST','STP','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (184,'SA','SAU','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (185,'SN','SEN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (186,'SC','SYC','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (187,'SL','SLE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (188,'SG','SGP','4');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (189,'SK','SVK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (190,'SI','SVN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (191,'SB','SLB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (192,'SO','SOM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (193,'ZA','ZAF','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (194,'GS','SGS','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (195,'ES','ESP','3');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (196,'LK','LKA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (197,'SH','SHN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (198,'PM','SPM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (199,'SD','SDN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (200,'SR','SUR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (201,'SJ','SJM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (202,'SZ','SWZ','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (203,'SE','SWE','5');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (204,'CH','CHE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (205,'SY','SYR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (206,'TW','TWN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (207,'TJ','TJK','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (208,'TZ','TZA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (209,'TH','THA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (210,'TG','TGO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (211,'TK','TKL','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (212,'TO','TON','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (213,'TT','TTO','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (214,'TN','TUN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (215,'TR','TUR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (216,'TM','TKM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (217,'TC','TCA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (218,'TV','TUV','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (219,'UG','UGA','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (220,'UA','UKR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (221,'AE','ARE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (222,'GB','GBR','6');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (223,'US','USA','2');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (224,'UM','UMI','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (225,'UY','URY','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (226,'UZ','UZB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (227,'VU','VUT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (228,'VA','VAT','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (229,'VE','VEN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (230,'VN','VNM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (231,'VG','VGB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (232,'VI','VIR','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (233,'WF','WLF','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (234,'EH','ESH','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (235,'YE','YEM','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (236,'RS','SRB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (238,'ZM','ZMB','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (239,'ZW','ZWE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (241,'PS','PSE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (242,'ME','MNE','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (243,'GG','GGY','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (244,'IM','IMN','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (245,'JE','JEY','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (246,'SS','SSD','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (247,'CW','CUW','1');
INSERT INTO countries (countries_id,countries_iso_code_2, countries_iso_code_3, address_format_id) VALUES (248,'SX','SXM','1');

INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(240, 1, 'Åland Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(1, 1, 'Afghanistan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(2, 1, 'Albania');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(3, 1, 'Algeria');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(4, 1, 'American Samoa');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(5, 1, 'Andorra');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(6, 1, 'Angola');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(7, 1, 'Anguilla');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(8, 1, 'Antarctica');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(9, 1, 'Antigua and Barbuda');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(10, 1, 'Argentina');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(11, 1, 'Armenia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(12, 1, 'Aruba');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(13, 1, 'Australia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(14, 1, 'Austria');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(15, 1, 'Azerbaijan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(16, 1, 'Bahamas');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(17, 1, 'Bahrain');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(18, 1, 'Bangladesh');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(19, 1, 'Barbados');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(20, 1, 'Belarus');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(21, 1, 'Belgium');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(22, 1, 'Belize');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(23, 1, 'Benin');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(24, 1, 'Bermuda');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(25, 1, 'Bhutan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(26, 1, 'Bolivia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(27, 1, 'Bosnia and Herzegowina');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(28, 1, 'Botswana');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(29, 1, 'Bouvet Island');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(30, 1, 'Brazil');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(31, 1, 'British Indian Ocean Territory');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(32, 1, 'Brunei Darussalam');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(33, 1, 'Bulgaria');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(34, 1, 'Burkina Faso');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(35, 1, 'Burundi');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(36, 1, 'Cambodia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(37, 1, 'Cameroon');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(38, 1, 'Canada');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(39, 1, 'Cape Verde');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(40, 1, 'Cayman Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(41, 1, 'Central African Republic');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(42, 1, 'Chad');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(43, 1, 'Chile');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(44, 1, 'China');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(45, 1, 'Christmas Island');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(46, 1, 'Cocos (Keeling) Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(47, 1, 'Colombia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(48, 1, 'Comoros');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(49, 1, 'Congo');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(50, 1, 'Cook Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(51, 1, 'Costa Rica');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(52, 1, "Côte d'Ivoire");
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(53, 1, 'Croatia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(54, 1, 'Cuba');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(55, 1, 'Cyprus');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(56, 1, 'Czech Republic');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(57, 1, 'Denmark');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(58, 1, 'Djibouti');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(59, 1, 'Dominica');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(60, 1, 'Dominican Republic');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(61, 1, 'Timor-Leste');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(62, 1, 'Ecuador');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(63, 1, 'Egypt');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(64, 1, 'El Salvador');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(65, 1, 'Equatorial Guinea');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(66, 1, 'Eritrea');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(67, 1, 'Estonia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(68, 1, 'Ethiopia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(69, 1, 'Falkland Islands (Malvinas)');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(70, 1, 'Faroe Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(71, 1, 'Fiji');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(72, 1, 'Finland');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(73, 1, 'France');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(75, 1, 'French Guiana');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(76, 1, 'French Polynesia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(77, 1, 'French Southern Territories');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(78, 1, 'Gabon');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(79, 1, 'Gambia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(80, 1, 'Georgia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(81, 1, 'Germany');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(82, 1, 'Ghana');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(83, 1, 'Gibraltar');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(84, 1, 'Greece');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(85, 1, 'Greenland');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(86, 1, 'Grenada');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(87, 1, 'Guadeloupe');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(88, 1, 'Guam');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(89, 1, 'Guatemala');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(90, 1, 'Guinea');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(91, 1, 'Guinea-bissau');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(92, 1, 'Guyana');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(93, 1, 'Haiti');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(94, 1, 'Heard and Mc Donald Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(95, 1, 'Honduras');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(96, 1, 'Hong Kong');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(97, 1, 'Hungary');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(98, 1, 'Iceland');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(99, 1, 'India');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(100, 1, 'Indonesia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(101, 1, 'Iran (Islamic Republic of)');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(102, 1, 'Iraq');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(103, 1, 'Ireland');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(104, 1, 'Israel');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(105, 1, 'Italy');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(106, 1, 'Jamaica');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(107, 1, 'Japan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(108, 1, 'Jordan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(109, 1, 'Kazakhstan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(110, 1, 'Kenya');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(111, 1, 'Kiribati');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(112, 1, "Korea, Democratic People's Republic of");
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(113, 1, 'Korea, Republic of');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(114, 1, 'Kuwait');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(115, 1, 'Kyrgyzstan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(116, 1, "Lao People's Democratic Republic");
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(117, 1, 'Latvia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(118, 1, 'Lebanon');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(119, 1, 'Lesotho');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(120, 1, 'Liberia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(121, 1, 'Libya');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(122, 1, 'Liechtenstein');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(123, 1, 'Lithuania');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(124, 1, 'Luxembourg');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(125, 1, 'Macao');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(126, 1, 'Macedonia, The Former Yugoslav Republic of');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(127, 1, 'Madagascar');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(128, 1, 'Malawi');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(129, 1, 'Malaysia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(130, 1, 'Maldives');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(131, 1, 'Mali');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(132, 1, 'Malta');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(133, 1, 'Marshall Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(134, 1, 'Martinique');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(135, 1, 'Mauritania');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(136, 1, 'Mauritius');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(137, 1, 'Mayotte');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(138, 1, 'Mexico');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(139, 1, 'Micronesia, Federated States of');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(140, 1, 'Moldova');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(141, 1, 'Monaco');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(142, 1, 'Mongolia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(143, 1, 'Montserrat');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(144, 1, 'Morocco');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(145, 1, 'Mozambique');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(146, 1, 'Myanmar');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(147, 1, 'Namibia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(148, 1, 'Nauru');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(149, 1, 'Nepal');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(150, 1, 'Netherlands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(151, 1, 'Bonaire, Sint Eustatius and Saba');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(152, 1, 'New Caledonia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(153, 1, 'New Zealand');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(154, 1, 'Nicaragua');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(155, 1, 'Niger');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(156, 1, 'Nigeria');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(157, 1, 'Niue');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(158, 1, 'Norfolk Island');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(159, 1, 'Northern Mariana Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(160, 1, 'Norway');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(161, 1, 'Oman');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(162, 1, 'Pakistan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(163, 1, 'Palau');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(164, 1, 'Panama');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(165, 1, 'Papua New Guinea');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(166, 1, 'Paraguay');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(167, 1, 'Peru');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(168, 1, 'Philippines');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(169, 1, 'Pitcairn');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(170, 1, 'Poland');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(171, 1, 'Portugal');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(172, 1, 'Puerto Rico');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(173, 1, 'Qatar');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(174, 1, 'Réunion');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(175, 1, 'Romania');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(176, 1, 'Russian Federation');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(177, 1, 'Rwanda');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(178, 1, 'Saint Kitts and Nevis');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(179, 1, 'Saint Lucia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(180, 1, 'Saint Vincent and the Grenadines');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(181, 1, 'Samoa');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(182, 1, 'San Marino');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(183, 1, 'Sao Tome and Principe');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(184, 1, 'Saudi Arabia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(185, 1, 'Senegal');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(186, 1, 'Seychelles');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(187, 1, 'Sierra Leone');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(188, 1, 'Singapore');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(189, 1, 'Slovakia (Slovak Republic)');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(190, 1, 'Slovenia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(191, 1, 'Solomon Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(192, 1, 'Somalia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(193, 1, 'South Africa');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(194, 1, 'South Georgia and the South Sandwich Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(195, 1, 'Spain');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(196, 1, 'Sri Lanka');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(197, 1, 'St. Helena');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(198, 1, 'St. Pierre and Miquelon');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(199, 1, 'Sudan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(200, 1, 'Suriname');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(201, 1, 'Svalbard and Jan Mayen Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(202, 1, 'Swaziland');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(203, 1, 'Sweden');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(204, 1, 'Switzerland');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(205, 1, 'Syrian Arab Republic');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(206, 1, 'Taiwan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(207, 1, 'Tajikistan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(208, 1, 'Tanzania, United Republic of');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(209, 1, 'Thailand');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(210, 1, 'Togo');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(211, 1, 'Tokelau');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(212, 1, 'Tonga');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(213, 1, 'Trinidad and Tobago');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(214, 1, 'Tunisia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(215, 1, 'Turkey');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(216, 1, 'Turkmenistan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(217, 1, 'Turks and Caicos Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(218, 1, 'Tuvalu');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(219, 1, 'Uganda');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(220, 1, 'Ukraine');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(221, 1, 'United Arab Emirates');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(222, 1, 'United Kingdom');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(223, 1, 'United States');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(224, 1, 'United States Minor Outlying Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(225, 1, 'Uruguay');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(226, 1, 'Uzbekistan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(227, 1, 'Vanuatu');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(228, 1, 'Vatican City State (Holy See)');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(229, 1, 'Venezuela');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(230, 1, 'Viet Nam');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(231, 1, 'Virgin Islands (British)');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(232, 1, 'Virgin Islands (U.S.)');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(233, 1, 'Wallis and Futuna Islands');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(234, 1, 'Western Sahara');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(235, 1, 'Yemen');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(236, 1, 'Serbia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(238, 1, 'Zambia');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(239, 1, 'Zimbabwe');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(241, 1, 'Palestine, State of');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(242, 1, 'Montenegro');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(243, 1, 'Guernsey');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(244, 1, 'Isle of Man');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(245, 1, 'Jersey');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(246, 1, 'South Sudan');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(247, 1, 'Curaçao');
INSERT INTO countries_name (countries_id, language_id, countries_name) VALUES(248, 1, 'Sint Maarten (Dutch part)');

# USA
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (1,223,'AL','Alabama');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (2,223,'AK','Alaska');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (3,223,'AS','American Samoa');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (4,223,'AZ','Arizona');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (5,223,'AR','Arkansas');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (7,223,'AA','Armed Forces Americas');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (9,223,'AE','Armed Forces Europe');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (11,223,'AP','Armed Forces Pacific');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (12,223,'CA','California');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (13,223,'CO','Colorado');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (14,223,'CT','Connecticut');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (15,223,'DE','Delaware');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (16,223,'DC','District of Columbia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (17,223,'FM','Federated States Of Micronesia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (18,223,'FL','Florida');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (19,223,'GA','Georgia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (20,223,'GU','Guam');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (21,223,'HI','Hawaii');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (22,223,'ID','Idaho');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (23,223,'IL','Illinois');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (24,223,'IN','Indiana');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (25,223,'IA','Iowa');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (26,223,'KS','Kansas');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (27,223,'KY','Kentucky');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (28,223,'LA','Louisiana');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (29,223,'ME','Maine');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (30,223,'MH','Marshall Islands');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (31,223,'MD','Maryland');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (32,223,'MA','Massachusetts');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (33,223,'MI','Michigan');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (34,223,'MN','Minnesota');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (35,223,'MS','Mississippi');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (36,223,'MO','Missouri');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (37,223,'MT','Montana');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (38,223,'NE','Nebraska');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (39,223,'NV','Nevada');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (40,223,'NH','New Hampshire');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (41,223,'NJ','New Jersey');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (42,223,'NM','New Mexico');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (43,223,'NY','New York');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (44,223,'NC','North Carolina');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (45,223,'ND','North Dakota');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (46,223,'MP','Northern Mariana Islands');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (47,223,'OH','Ohio');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (48,223,'OK','Oklahoma');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (49,223,'OR','Oregon');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (50,163,'PW','Palau');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (51,223,'PA','Pennsylvania');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (52,223,'PR','Puerto Rico');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (53,223,'RI','Rhode Island');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (54,223,'SC','South Carolina');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (55,223,'SD','South Dakota');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (56,223,'TN','Tennessee');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (57,223,'TX','Texas');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (58,223,'UT','Utah');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (59,223,'VT','Vermont');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (60,223,'VI','Virgin Islands');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (61,223,'VA','Virginia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (62,223,'WA','Washington');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (63,223,'WV','West Virginia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (64,223,'WI','Wisconsin');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (65,223,'WY','Wyoming');

# Canada
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (66,38,'AB','Alberta');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (67,38,'BC','British Columbia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (68,38,'MB','Manitoba');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (69,38,'NL','Newfoundland');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (70,38,'NB','New Brunswick');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (71,38,'NS','Nova Scotia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (72,38,'NT','Northwest Territories');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (73,38,'NU','Nunavut');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (74,38,'ON','Ontario');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (75,38,'PE','Prince Edward Island');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (76,38,'QC','Quebec');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (77,38,'SK','Saskatchewan');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (78,38,'YT','Yukon Territory');

# Germany
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (79,81,'NDS','Niedersachsen');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (80,81,'BAW','Baden-Wurttemberg');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (81,81,'BAY','Bayern');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (82,81,'BER','Berlin');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (83,81,'BRG','Brandenburg');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (84,81,'BRE','Bremen');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (85,81,'HAM','Hamburg');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (86,81,'HES','Hessen');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (87,81,'MEC','Mecklenburg-Vorpommern');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (88,81,'NRW','Nordrhein-Westfalen');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (89,81,'RHE','Rheinland-Pfalz');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (90,81,'SAR','Saarland');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (91,81,'SAS','Sachsen');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (92,81,'SAC','Sachsen-Anhalt');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (93,81,'SCN','Schleswig-Holstein');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (94,81,'THE','Thringen');

# Austria
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (95,14,'WI','Wien');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (96,14,'NO','Niedersterreich');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (97,14,'OO','Obersterreich');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (98,14,'SB','Salzburg');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (99,14,'KN','Karnten');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (100,14,'ST','Steiermark');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (101,14,'TI','Tirol');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (102,14,'BL','Burgenland');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (103,14,'VB','Voralberg');

# Swizterland
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (104,204,'AG','Aargau');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (105,204,'AI','Appenzell Innerrhoden');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (106,204,'AR','Appenzell Ausserrhoden');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (107,204,'BE','Bern');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (108,204,'BL','Basel-Landschaft');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (109,204,'BS','Basel-Stadt');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (110,204,'FR','Freiburg');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (111,204,'GE','Genf');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (112,204,'GL','Glarus');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (113,204,'JU','Graubnden');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (114,204,'JU','Jura');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (115,204,'LU','Luzern');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (116,204,'NE','Neuenburg');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (117,204,'NW','Nidwalden');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (118,204,'OW','Obwalden');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (119,204,'SG','St. Gallen');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (120,204,'SH','Schaffhausen');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (121,204,'SO','Solothurn');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (122,204,'SZ','Schwyz');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (123,204,'TG','Thurgau');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (124,204,'TI','Tessin');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (125,204,'UR','Uri');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (126,204,'VD','Waadt');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (127,204,'VS','Wallis');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (128,204,'ZG','Zug');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (129,204,'ZH','Zurich');

# Spain
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'A Coruna','A Coruna');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Alava','Alava');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Albacete','Albacete');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Alicante','Alicante');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Almeria','Almeria');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Asturias','Asturias');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Avila','Avila');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Badajoz','Badajoz');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Baleares','Baleares');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Barcelona','Barcelona');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Burgos','Burgos');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Caceres','Caceres');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Cadiz','Cadiz');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Cantabria','Cantabria');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Castellon','Castellon');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Ceuta','Ceuta');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Ciudad Real','Ciudad Real');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Cordoba','Cordoba');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Cuenca','Cuenca');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Girona','Girona');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Granada','Granada');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Guadalajara','Guadalajara');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Guipuzcoa','Guipuzcoa');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Huelva','Huelva');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Huesca','Huesca');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Jaen','Jaen');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'La Rioja','La Rioja');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Las Palmas','Las Palmas');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Leon','Leon');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Lleida','Lleida');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Lugo','Lugo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Madrid','Madrid');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Malaga','Malaga');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Melilla','Melilla');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Murcia','Murcia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Navarra','Navarra');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Ourense','Ourense');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Palencia','Palencia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Pontevedra','Pontevedra');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Salamanca','Salamanca');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Santa Cruz de Tenerife','Santa Cruz de Tenerife');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Segovia','Segovia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Sevilla','Sevilla');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Soria','Soria');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Tarragona','Tarragona');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Teruel','Teruel');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Toledo','Toledo');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Valencia','Valencia');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Valladolid','Valladolid');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Vizcaya','Vizcaya');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Zamora','Zamora');
INSERT INTO zones (zone_country_id, zone_code, zone_name) VALUES (195,'Zaragoza','Zaragoza');

#australian zones
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'ACT', 'Australian Capital Territory');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'NSW', 'New South Wales');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'NT', 'Northern Territory');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'QLD', 'Queensland');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'SA', 'South Australia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'TAS', 'Tasmania');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'VIC', 'Victoria');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 13, 'WA', 'Western Australia');

#italian zones
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AG','Agrigento');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AL','Alessandria');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AN','Ancona');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AO','Aosta');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AR','Arezzo');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AP','Ascoli Piceno');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AT','Asti');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AV','Avellino');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BA','Bari');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BT','Barletta Andria Trani');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BL','Belluno');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BN','Benevento');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BG','Bergamo');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BI','Biella');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BO','Bologna');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BZ','Bolzano');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BS','Brescia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'BR','Brindisi');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CA','Cagliari');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CL','Caltanissetta');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CB','Campobasso');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CI','Carbonia-Iglesias');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CE','Caserta');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CT','Catania');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CZ','Catanzaro');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CH','Chieti');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CO','Como');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CS','Cosenza');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CR','Cremona');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'KR','Crotone');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'CN','Cuneo');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'EN','Enna');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'FM','Fermo');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'FE','Ferrara');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'FI','Firenze');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'FG','Foggia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'FC','Forli Cesena');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'FR','Frosinone');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'GE','Genova');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'GO','Gorizia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'GR','Grosseto');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'IM','Imperia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'IS','Isernia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'AQ','Aquila');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'SP','La Spezia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'LT','Latina');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'LE','Lecce');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'LC','Lecco');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'LI','Livorno');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'LO','Lodi');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'LU','Lucca');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'MC','Macerata');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'MN','Mantova');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'MS','Massa Carrara');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'MT','Matera');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VS','Medio Campidano');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'ME','Messina');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'MI','Milano');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'MO','Modena');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'MB','Monza e Brianza');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'NA','Napoli');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'NO','Novara');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'NU','Nuoro');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'OG','Ogliastra');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'OT','Olbia-Tempio');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'OR','Oristano');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PD','Padova');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PA','Palermo');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PR','Parma');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PG','Perugia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PV','Pavia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PU','Pesaro Urbino');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PE','Pescara');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PC','Piacenza');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PI','Pisa');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PT','Pistoia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PN','Pordenone');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PZ','Potenza');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'PO','Prato');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RG','Ragusa');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RA','Ravenna');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RC','Reggio Calabria');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RE','Reggio Emilia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RI','Rieti');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RN','Rimini');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RM','Roma');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'RO','Rovigo');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'SA','Salerno');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'SS','Sassari');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'SV','Savona');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'SI','Siena');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'SR','Siracusa');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'SO','Sondrio');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TA','Taranto');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TE','Teramo');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TR','Terni');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TO','Torino');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TP','Trapani');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TN','Trento');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TV','Treviso');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'TS','Trieste');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'UD','Udine');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VA','Varese');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VE','Venezia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VB','Verbania');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VC','Vercelli');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VR','Verona');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VV','Vibo Valentia');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VI','Vicenza');
INSERT INTO zones (zone_id, zone_country_id, zone_code, zone_name) VALUES (NULL, 105,'VT','Viterbo');

